### PR TITLE
fix(secret-service): Deleting a secret does not remove references from related roles

### LINKED ISSUE #7786: secret-service: Deleting a secret does not remove it from the respective role
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.14.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): K3d 1.21
* Kubernetes version (`kubectl version`): 1.21

**Affected Component**

* [x] secret-service

**Describe the bug**

When deleting a secret, it is not removed from the respective role. Worst-case, we end up having the same secret multiple times within the role.

**To Reproduce**

* Create secret
```bash
$ keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE" 
```
* Verify role
```bash
$ kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
...
rules:
- apiGroups:
  - ""
  resourceNames:
  - secret-1
  resources:
  - secrets
  verbs:
  - get
```
* Delete secret
```bash
$ keptn delete secret secret-1
```
* Verify role again - secret-1 is still in there
* Add secret again
```bash
$ keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE" 
```
* Verify role
```bash
rules:
- apiGroups:
  - ""
  resourceNames:
  - secret-1
  - secret-1
  resources:
  - secrets
  verbs:
  - get

```

**Expected behavior**

`secret-1` should be removed when we call `keptn delete secret`

**Current behavior**

`secret-1` stays in the role, and is duplicated over and over again

### PR DESCRIPTION
**Pull request by warber**
fixes #7786
latest integration test run: https://github.com/keptn/keptn/runs/6489169782?check_suite_focus=true

Create two secrets:
```
keptn create secret secret-1 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE"
keptn create secret secret-2 --scope="keptn-prometheus-service" --from-literal="KEY=VALUE"
``` 

Check role  (expect 2 refs):
```
kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
...
rules:
- apiGroups:
  - ""
  resourceNames:
  - secret-1
  - secret-2
  resources:
  - secrets
  verbs:
  - get
``` 

Delete secret without specifying the scope (expect error):
```
keptn delete secret secret-1
...
Error: Unable to delete secret: could not delete secret secret-1 in scope keptn-default: secret not found
```

Delete first secret:
```
keptn delete secret secret-1 --scope keptn-prometheus-service
``` 

Check role  (expect resp. ref removed):
```
kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
...
- apiGroups:
  - ""
  resourceNames:
  - secret-2
  resources:
  - secrets
  verbs:
  - get
``` 

Delete second secret:
```
keptn delete secret secret-2 --scope keptn-prometheus-service
``` 

Check role (expect whole role removed):
```
kubectl -n keptn get role keptn-prometheus-svc-read -oyaml
Error from server (NotFound): roles.rbac.authorization.k8s.io "keptn-prometheus-svc-read" not found
```

### CODE REVIEW

File: secret-service/pkg/backend/secretbackend_k8s.go [hunk 1]
```diff
@@ -117,32 +117,33 @@ func (k K8sSecretBackend) DeleteSecret(secret model.Secret) error {
...
-	// delete associated roles and rolebinding
+
+	// if there is no secret with that scope
+	// do nothing and return
 	if len(secretsWithScope.Items) == 0 {
+		return fmt.Errorf("could not delete secret %s in scope %s: %w", secret.Name, secret.Scope, ErrSecretNotFound)
+	}
+
+	// if it is the last secret with that scope
+	// we can wipe all associated roles and rolebinding
```
Comment (mowies) [inline secret-service/pkg/backend/secretbackend_k8s.go:133]:
```suggestion
	// we can wipe all associated roles and rolebindings
```
:)

File: secret-service/pkg/backend/secretbackend_k8s.go [hunk 2]
```diff
@@ -117,32 +117,33 @@ func (k K8sSecretBackend) DeleteSecret(secret model.Secret) error {
...
 			log.Warnf("Unable to delete roles: %s", err.Error())
 		}
 		if err := k.KubeAPI.RbacV1().RoleBindings(namespace).DeleteCollection(context.TODO(), metav1.DeleteOptions{}, metav1.ListOptions{LabelSelector: "app.kubernetes.io/scope=" + secret.Scope}); err != nil {
 			log.Warnf("Unable to delete role bindings: %s", err.Error())
 		}
-	} else {
+	}
+
+	// if there are still more secrets associated to that scope
+	// we need to update the refs in the roles and the role bindings
```
Comment (odubajDT) [inline secret-service/pkg/backend/secretbackend_k8s.go:145]: rolebindings

**Review by odubajDT — APPROVED** [review]
lgtm
