### PR TITLE
Load traces in the sequence screen for not selected sequences

### LINKED ISSUE #4051: Sequence is only updated when detail is opened
**Describe the bug**
When starting a delivery the entry in the sequence list is only updated properly when clicking on the detail. Otherwise it will appear and stay in state running.

**To Reproduce**
1. Trigger a delivery
2. Switch to any screen and back to sequences, so that no sequence is pre-selected
3. Sequence will appear
4. Open sequence in second tab, and open detail
5. Wait until the sequence is finished
6. Observe the tab, where no detail is selected - the sequence is not updated

**Expected behavior**
The sequence gets updated also when no sequence detail is selected

A note here: It seems to work for evaluations

### PR DESCRIPTION
**Pull request by laneli**
Fixes #4051

The traces of the sequences were only loaded when a detail was opened.
Now it checks regularly, if there are any running sequences and loads traces for them.
Also the currently selected sequence is also excluded by this mechanism, because it gets already loaded.

Signed-off-by: Elisabeth Lang <elisabeth.lang@dynatrace.com>

### CODE REVIEW

File: bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts [hunk 1]
```diff
@@ -104,31 +109,45 @@ export class KtbSequenceViewComponent implements OnInit, OnDestroy {
...
-              this._filterDataSource.data = this.filterFieldData;
-            }
-            this._changeDetectorRef.markForCheck();
-          });
+              if (roots) {
+                this.updateFilterSequence(roots);
+                this._filterDataSource.data = this.filterFieldData;
+                // Set unfinished roots so that the traces for updates can be loaded
+                // Also ignore currently selected root, as this is getting already polled
+                this.unfinishedRoots = roots.filter(root => !!root && root.traces.some(r => r.finished !== undefined && !r.finished)).filter(root => this.currentSequence !== root);
```
Comment (Kirdock) [inline bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:146]: Suggestion:
Change it to `this.unfinishedRoots = roots.filter(root => root && !root.isFinished() && root !==  this.currentSequence)`

Comment (laneli) [reply bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts]: Changed and tested. Thanks for the input :)

**Comment by Kirdock** [comment]
Currently new roots are not updated correctly.
Cause:
https://github.com/keptn/keptn/blob/7e918ea3f328d254d956248c3ab3a772bc5777a8/bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts#L170-L176

The timer is unsubscribed every time before it is finished. In addition to that there is the same timer for all unfinished roots

File: bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts [hunk 2]
```diff
@@ -104,31 +109,45 @@ export class KtbSequenceViewComponent implements OnInit, OnDestroy {
...
             this.updateFilterDataSource(project);
 
+            this.dataService.loadRoots(project);
+
+            this._rootsTimer = timer(0, this._tracesTimerInterval*1000)
+              .pipe(takeUntil(this.unsubscribe$))
+              .subscribe(() => {
+                // This triggers the subscription for roots$
+                this.unfinishedRoots?.forEach(root => {
+                  this.loadTraces(root);
```
Comment (Kirdock) [inline bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:119]: Change it to `this.dataService.loadTraces(root);`

**Review by Kirdock — APPROVED** [review]
