### PR TITLE
#2430 Fixed broken link

### LINKED ISSUE #2430: Click on Keptn API > page not found
I installed a preview of Keptn 0.7.2 

When clicking on  `Keptn API`, I get forwarded to:
```
{"code":404,"message":"path / was not found"}
```

**Fix:**
- Remove / from the path

**Enhancement:**
- Can we please flip the links. 
  - Advantage: it then shows them in the same order like the copy/paste labels below. (goal: red, blue, red, blue arrows)
image

### PR DESCRIPTION
**Pull request by johannes-b**
Closes #2430

### CODE REVIEW

**Comment by johannes-b** [comment]
The link works and I changed the order:

image

@ermin-muratovic Can I ask you for a review, please?

File: bridge/server/api/index.js [hunk 1]
```diff
@@ -30,7 +30,7 @@ module.exports = (params) => {
     try {
       const result = await axios({
         method: req.method,
-        url: `${apiUrl}${req.url}`,
+        url: `${apiUrl}/${req.url}`,
```
Comment (johannes-b) [inline bridge/server/api/index.js:33]: @ermin-muratovic Is this change correct? (also see line 66)

Comment (ermin-muratovic) [reply bridge/server/api/index.js:33]: This `/` here is not necessary, because `req.url` starts with a `/` and therefore you would get a double `/` here.
And the `apiUrl` in the server-part actually has not changed. (same on line 66)

**Review by ermin-muratovic — CHANGES_REQUESTED** [review]
Since the `apiUrl` in the server has not changed and usually is just the internal URL to the api service, that `/` there is not necessary.
The changes in the client are fine.

**Comment by johannes-b** [comment]
Thanks for the feedback - I reverted the server code.

**Review by ermin-muratovic — APPROVED** [review]
lgtm
