### PR TITLE
fix(shipyard-controller): Return `ErrProjectNotFound` instead of `nil, nil` when project is not in the db

### LINKED ISSUE #8242: Shipyard-controller 0.14.2 crashes with panic
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Ubuntu-20.04 (GitHub runner)
* Keptn Version (`keptn version`): 0.14.2
* Kubernetes Cloud Provider (e.g., GKE, AKS): v1.21.12+k3s1
* Kubernetes version (`kubectl version`): -

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
Sometimes the integration tests for the job-executor-service are not successful, because nginx returns a 502 Bad Gateway error as shown in this [run](https://github.com/keptn-contrib/job-executor-service/runs/7105245137?check_suite_focus=true#step:13:57).

This seem to happen when deleting a project:
```
2022/06/29 04:10:25 [error] 33#33: *921 upstream prematurely closed connection while reading response header from upstream, client: 10.42.0.1, server: _, request: "DELETE /api/controlPlane/v1/project/jes-locust HTTP/1.1", upstream: "http://10.43.218.236:8080/v1/project/jes-locust", host: "10.1.0.93"
10.42.0.1 - - [29/Jun/2022:04:10:25 +0000] "DELETE /api/controlPlane/v1/project/jes-locust HTTP/1.1" 502 150 "-" "Go-http-client/1.1"
2022/06/29 04:10:25 [error] 35#35: *1054 connect() failed (111: Connection refused) while connecting to upstream, client: 10.42.0.1, server: _, request: "POST /api/controlPlane/v1/project HTTP/1.1", upstream: "http://10.43.218.236:8080/v1/project", host: "10.1.0.93"
```

The cause of that behavior seems to be a crash of the shipyard-controller:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x162c9ec]

goroutine 5822 [running]:
github.com/keptn/keptn/shipyard-controller/handler.(*ShipyardRetriever).GetCachedShipyard(0xeda4dc7b1, {0xc00048a850, 0x0})
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardretriever.go:71 +0x2c
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).triggerNextTaskSequences(_, {{{0xc00048a850, 0xa}, {0xc00048a86c, 0x2}, {0xc00048a860, 0xc}, 0x0, {0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:720 +0x63
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).proceedTaskSequence(_, {{{0xc00048a850, 0xa}, {0xc00048a86c, 0x2}, {0xc00048a860, 0xc}, 0x0, {0x0, 0x0}, ...}, ...}, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:699 +0x308
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).onTaskProgress(_, {{0x0, 0x0}, {0x18927c0, 0xc000803f80}, {0x0, 0x0}, {0xc0006af920, 0x24}, {0xc0006af950, ...}, ...}, ...)
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:373 +0x5e5
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).handleTaskEvent(0xc000103860, {{0x0, 0x0}, {0x18927c0, 0xc000803f80}, {0x0, 0x0}, {0xc0006af920, 0x24}, {0xc0006af950, ...}, ...})
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:316 +0x2e8
github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent.func2()
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:168 +0x65
created by github.com/keptn/keptn/shipyard-controller/handler.(*shipyardController).HandleIncomingEvent
	/go/src/github.com/keptn/keptn/shipyard-controller/handler/shipyardcontroller.go:167 +0x4d1

[...]
```

For the full context please see the have a look at [keptn-support-archive-0.14.2-netpolicy-false-jobnetpolicy-true.zip](https://github.com/keptn/keptn/files/9008303/keptn-support-archive-0.14.2-netpolicy-false-jobnetpolicy-true.zip)

**To Reproduce**

I'm not able to consistently reproduce the error locally or with any other integration test runs

**Expected behavior**

Project is deleted and the shipyard-controller can still process other requests without crashing

**Current behavior**

The shipyard-controller crashes and renders the keptn installation unusable for the remaining time of the integration test run

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #8242

Note: The section of the shipyard retriever mentioned in the bug ticket now can rely on the project not being nil in case no error is returned by `projectRepo.GetProject()`.  Previously this returned `nil, nil`, which caused the nil pointer access shipyard retriever

### CODE REVIEW

File: shipyard-controller/handler/projectmanager.go [hunk 1]
```diff
@@ -166,6 +161,18 @@ func (pm *ProjectManager) Create(params *models.CreateProjectParams) (error, com
...
 }
 
+func (pm *ProjectManager) checkForExistingProject(params *models.CreateProjectParams) error {
+	existingProject, err := pm.ProjectMaterializedView.GetProject(*params.Name)
+	if err != nil && err != db.ErrProjectNotFound {
+		log.Errorf("Error occurred while getting project: %s", err.Error())
+		return fmt.Errorf("failed to get project: '%s'", *params.Name)
+	}
+	if existingProject != nil {
+		return ErrProjectAlreadyExists
```
Comment (warber) [inline shipyard-controller/handler/projectmanager.go:171]:
```suggestion
		return fmt.Errorf("failed to get project: '%s': %w",*params.Name,ErrProjectAlreadyExists)
```

**Review by warber — APPROVED** [review]
