### PR TITLE
fix(bridge): Add missing update project notification

### LINKED ISSUE #7769: Bridge: Missing notification when project is updated
Currently, if the resource service is enabled, the update notification is missing when the git upstream is updated

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #7769
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts [hunk 1]
```diff
@@ -105,6 +111,10 @@ export class KtbProjectSettingsGitExtendedComponent implements OnInit {
       this.dataService.updateGitUpstream(this.projectName, this.gitData).subscribe(
```
Comment (renepanzar) [inline bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts:111]: Shouldn't this subscription be unsubscribed at some point? Might be a dangling subscription, did not find anything in the documentation on HttpClient, though...

Comment (renepanzar) [reply bridge/client/app/_components/ktb-project-settings-git-extended/ktb-project-settings-git-extended.component.ts:111]: ``OK, i saw it in the source: https://github.com/angular/angular/blob/986e80e9db46a267d33667464bb64c3501f8c72b/packages/common/http/src/xhr.ts#L193

```
        if (ok) {
          // A successful response is delivered on the event stream.
          observer.next(new HttpResponse({
            body,
            headers,
            status,
            statusText,
            url: url || undefined,
          }));
          // The full body has been received and delivered, no further events
          // are possible. This request is complete.
          observer.complete();
        } else {
```

**Review by renepanzar — APPROVED** [review]
LGTM!
