### PR TITLE
fix(cli): skip version check on install

### LINKED ISSUE #3158: cli: keptn version checking on install
**Environment**

* Client OS (e.g., Linux, OSX, Windows): `linux`
* Keptn Version (`keptn version`): `develop` (pulled latest from master at git head 22ec97a7d988c0b13f8ff9fb62730a438534c587 )
* Kubernetes Cloud Provider (e.g., GKE, AKS): `minikube` (local cluster)

**Affected Component**

* [ ] Docs
* [x] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**

keptn cli attempts to check keptn cluster version while installation of keptn.

This would always throw an error, because keptn cluster wouldn't be there in the first place without installation.

**To Reproduce**
```bash
git clone https://github.com/keptn/keptn
cd keptn/cli
minikube start
go build -o keptn
./keptn install
```

1. The error would be visible as soon as you run `./keptn install`

**Expected behavior**
Ask confirmation for the cluster and proceed with keptn installation.

**Current behavior**
First checks keptn cluster version, which will always fail, then asks for confirmation for cluster and proceeds with keptn installation.

**Screenshots**
keptn_cli_version_error

If this is deemed as an actual bug, I would like to investigate and send a PR regarding the same :smiley:

### PR DESCRIPTION
**Pull request by vadasambar**
## This PR

- skips version check on `keptn install`

### Related Issues

Fixes #3158

### How to test

1. Run `keptn install` locally without a cluster running. You should not see a `Warning` message like [this](https://user-images.githubusercontent.com/31009634/106847806-ace9c200-66d5-11eb-96c8-1b3a5540de79.png).
2. Run any other command like `keptn auth` or `keptn uninstall` without a cluster running and you should see a `Warning` message like [this](https://user-images.githubusercontent.com/31009634/106847806-ace9c200-66d5-11eb-96c8-1b3a5540de79.png).

### CODE REVIEW

File: cli/cmd/root.go [hunk 1]
```diff
@@ -32,7 +33,11 @@ func NewRootCommand(vChecker *version.VersionChecker) *cobra.Command {
 		Long: `The CLI allows interaction with a Keptn installation to manage Keptn, to trigger workflows, and to get details.
 	`,
 		PersistentPreRun: func(cmd *cobra.Command, args []string) {
```
Comment (vadasambar) [inline cli/cmd/root.go:35]: `PersistentPreRun` cannot be skipped conditionally based on the subcomand.

**Comment by johannes-b** [comment]
Hello @vadasambar,
thanks for working on this issue. Can you please address the broken unit test: https://github.com/keptn/keptn/pull/5046/checks?check_run_id=3492104219?

**Comment by vadasambar** [comment]
Hey @johannes-b, thank you for the comment. I have fixed the test.

File: cli/cmd/root.go [hunk 2]
```diff
@@ -111,7 +113,13 @@ func (s *options) appendIfNotEmpty(newOption string) {
 	}
 }
 
-func runVersionCheck(vChecker *version.VersionChecker) {
+func runVersionCheck(vChecker *version.VersionChecker, flags []string) {
+	// Server version won't be available during `install`
+	// because the Server is not installed yet
+	if isInstallSubCommand(flags) {
```
Comment (vadasambar) [inline cli/cmd/root.go:119]: Doing this in `runVersionCheck` instead of `PersistentRun` because it is easier to test `runVersionCheck` (we already have code for doing this [here](https://github.com/keptn/keptn/blob/d1555f9f6882742d3d26dd4157358e6769548fb7/cli/cmd/root_test.go#L148))

File: cli/cmd/root.go [hunk 3]
```diff
@@ -143,3 +151,19 @@ func runVersionCheck(vChecker *version.VersionChecker) {
 		updateLastVersionCheck()
 	}
 }
+
+func isInstallSubCommand(flags []string) bool {
```
Comment (vadasambar) [inline cli/cmd/root.go:155]: TODO: Use a different variable name here. `flags` here means flags like `-q` and subcommands like `install` in a slice e.g., `[]string{"-q", "install"}`

File: cli/cmd/root_test.go [hunk 4]
```diff
@@ -194,6 +197,49 @@ func Test_runVersionCheck(t *testing.T) {
 			metadataStatus: http.StatusInternalServerError,
 			wantOutput:     "* Warning: could not check Keptn server version: received invalid response from Keptn API\n",
 		},
+		{
+			name:            "skip version check for 'keptn install'",
```
Comment (vadasambar) [inline cli/cmd/root_test.go:201]: I am writing unit tests related `keptn install` in `root_test.go` because the code to skip version check on `install` subcommand is in `root.go`.

File: cli/cmd/root_test.go [hunk 5]
```diff
@@ -177,7 +178,9 @@ func Test_runVersionCheck(t *testing.T) {
 		metadataStatus   int
 		metadataResponse keptnapimodels.Metadata
 		cliVersion       string
+		flags            []string
```
[the remark this answers is not in the document]
Comment (vadasambar) [reply cli/cmd/root_test.go]: Done

File: cli/cmd/root.go (hunk 3 above)
Comment (vadasambar) [reply cli/cmd/root.go]: Done

**Review by bacherfl — APPROVED** [review]
lgtm
