### PR TITLE
#2877 cli: better keptn auth messages

### LINKED ISSUE #2877: Extend keptn auth with more doc output to explain how to obtain token & endpoint
This could be an easy win for user experience. When doing a keptn auth the current output says 
```
Error: required flag(s) "api-token", "endpoint" not set
```

Would be better to reflect some of the documentation or at least point to the doc where we explain how to get token and endpoint
Here is a version that I think would help:
```
$ keptn auth
keptn auth requires api-token and endpoint.

For more information on how to obtain token and endpoint to go https://keptn.sh/docs/0.7.x/reference/cli/#authenticate-keptn-cli
```

### PR DESCRIPTION
**Pull request by DarthBenro008**
- Fixes #2877 

### Preview

keptn_auth_endpoint_message

### CODE REVIEW

File: cli/cmd/auth.go [hunk 1]
```diff
@@ -148,6 +148,13 @@ func init() {
 }
 
 func verifyAuthParams(authParams *authCmdParams) error {
+
+	const parametersRequiredMessage = "keptn auth requires api-token and endpoint \n\n" +
+		"For more information on how to obtain token and endpoint to go https://keptn.sh/docs/%s/reference/cli/#authenticate-keptn-cli \n\n" +
+		"Alternatively,To quickly access Keptn, you can use a port-forward and then authenticate your Keptn CLI: \n" +
```
Comment (christian-kreuzberger-dtx) [inline cli/cmd/auth.go:154]: I think there is a space missing between *Alternatively,* and *To*. Also, *To* should be lowercased *to*

File: cli/cmd/auth.go [hunk 2]
```diff
@@ -148,6 +148,13 @@ func init() {
...
+		"- kubectl -n keptn port-forward service/api-gateway-nginx 8080:80 \n" +
```
Comment (christian-kreuzberger-dtx) [inline cli/cmd/auth.go:155]: Is it possible to make the namespace a variable here?

File: cli/cmd/auth.go [hunk 3]
```diff
@@ -229,7 +249,7 @@ func smartKeptnCLIAuth() (string, error) {
 	}
 
 	if len(keptnInstallations) > 1 {
-		fmt.Println("We have found multiple Keptn Installation, Please select the one from the list below to continue")
+		fmt.Println("We have found multiple Keptn Installations, Please select the one from the list below to continue")
```
Comment (christian-kreuzberger-dtx) [inline cli/cmd/auth.go:252]: please change to
> There are multiple Keptn installations on your Kubernetes cluster, please select the correct one from the list below to continue

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]
Thanks for the PR. Please adress my comments :)

File: cli/cmd/auth.go (hunk 2 above)
Comment (DarthBenro008) [reply cli/cmd/auth.go:155]: By making the namespace variable, my understanding it that we want fetch and show the namespace that keptn is installed in (passed in args of `keptn install`)?
If that is the case, we will have to write a separate function that detects the installation namespace.

But in my opinion, whosoever follows the tutorial, they will probably have the default installation namespace as `keptn`.

Do let me know your thoughts!

File: cli/cmd/auth.go (hunk 1 above)
Comment (DarthBenro008) [reply cli/cmd/auth.go]: Fixed in 42c037f666185b728f27f042d7e3faca704c5ec5 !

File: cli/cmd/auth.go (hunk 2 above)
Comment (christian-kreuzberger-dtx) [reply cli/cmd/auth.go:155]: I agree that most people will follow the tutorial where you install it in the `keptn` namespace, nevertheless, I think the variable `namespace` is available (see line `namespace, err = smartKeptnCLIAuth()`), so we could make use of that (and in case it is empty or an has occured when fetching it, it could default to `keptn`).

So my proposal would be:
```
namespace := "keptn"
namespace, err = smartKeptnCLIAuth()
...
return fmt.Errorf(err.Error()+parametersRequiredMessage, keptnReleaseDocsURL, namespace)
```

**Comment by DarthBenro008** [comment]
Hey @christian-kreuzberger-dtx ,

I have tested and added variable namespacing the message. Apparently we the fallback to default keptn namespace is already handled and we do not need to define it again (tested)

Here is the message when keptn is installed in a custom namespace called `testnamespace`:

namespace_variable

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM
