### PR TITLE
fix(shipyard-controller): Allow parallel sequence execution if the service is different

### LINKED ISSUE #7753: Sequences from one service blocks sequence of another service
**Environment**

* Keptn Version (`keptn version`): `0.15.0` (but probably older releases too)

**Affected Component**

* [x] Shipyard-controller

**Describe the bug**

* A sequence from one service is blocking the sequence from another service: 

image

**To Reproduce**

* Trigger, e.g., a delivery sequence for two services at the same time: 

```
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.3
keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo:4.2.2 --sequence=delivery-direct
```

* Delivery of carts is blocking carts-db. 

## Expected behavior
* Both sequences (for `carts` & `carts-db`) are running in parallel as described here: https://github.com/keptn/keptn/issues/3776#issuecomment-878877717

image

## Related discussions

- https://github.com/keptn/enhancement-proposals/issues/79

### PR DESCRIPTION
**Pull request by RealAnna**
## This PR

-  dispatcher allows parallel sequences on the same project and stage if at least the service is different.
-  adds unit test
-  adds integration test

### Related Issues

Fixes #7753 
https://github.com/keptn/keptn/actions/runs/2344206480

### CODE REVIEW

File: test/go-tests/testsuite_gke_test.go [hunk 1]
```diff
@@ -17,6 +17,7 @@ func Test_GKE(t *testing.T) {
 	t.Run("Test_LogForwarding", Test_LogForwarding)
 	t.Run("Test_SequenceState", Test_SequenceState)
 	t.Run("Test_SequenceStateParallelStages", Test_SequenceStateParallelStages)
+	t.Run("Test_SequenceStateParallelServices", Test_SequenceStateParallelServices)
```
Comment (odubajDT) [inline test/go-tests/testsuite_gke_test.go:20]: why only GKE? I think we should run them for all platforms

Comment (RealAnna) [reply test/go-tests/testsuite_gke_test.go:20]: true I'll copy it everywhere :)

**Review by odubajDT — COMMENTED** [review]
lgtm

**Review by odubajDT — APPROVED** [review]
