### PR TITLE
fix(shipyard-controller): Update complete sequence execution after sequence is finished

### LINKED ISSUE #8808: Shipyard Controller: `previousTasks` property of  Sequence Execution model is not updated after last task of a sequence
As seen in the following example of a sequence execution returned by the `v1/controlPlane/sequence-execution` endpoint, the returned sequence execution is finished, but the result of the last task of that sequence is in the `currentTask` property:

```
{
      "_id": "d19f8a18-be97-43e4-96f7-a50ed27eec59",
      "schemaVersion": "1",
      "sequence": {
        "name": "evaluation",
        "tasks": [
          {
            "name": "evaluation",
            "properties": null
          }
        ]
      },
      "status": {
        "state": "finished",
        "stateBeforePause": "",
        "previousTasks": [],
        "currentTask": {
          "name": "evaluation",
          "triggeredID": "76de2b36-41a7-4168-a8eb-0a09e6e2082c",
          "events": [
            {
              "eventType": "sh.keptn.event.evaluation.started",
              "source": "lighthouse-service",
              "result": "",
              "status": "succeeded",
              "time": "2022-08-24T07:59:35.250Z",
              "properties": null
            },
            {
              "eventType": "sh.keptn.event.evaluation.finished",
              "source": "lighthouse-service",
              "result": "pass",
              "status": "succeeded",
              "time": "2022-08-24T08:00:04.582Z",
              "properties": {
                "evaluation": {
                  "result": "pass",
                  "score": 100,
                },
                "project": "keptn-quality-gates",
                "result": "pass",
                "service": "my-service",
                "stage": "hardening",
                "status": "succeeded"
              }
            }
          ]
        }
      },
      "scope": {
        "project": "keptn-quality-gates",
        "stage": "hardening",
        "service": "my-service",
        "keptnContext": "030a3a8e-e270-4608-a04a-a1771155319a",
        "triggeredId": "16684b29-6ae3-4b17-aea1-56182ae8a5ce",
        "gitcommitid": "0e4b2c4d36223f89054373b2c5a489e39dfb32ca",
        "eventType": "sh.keptn.event.hardening.evaluation.triggered"
      },
      "inputProperties": {
        "deployment": {
          "deploymentNames": null
        },
        "evaluation": {
          "end": "2022-01-26T10:10:53.931Z",
          "start": "2022-01-26T10:05:53.931Z",
          "timeframe": ""
        },
        "project": "keptn-quality-gates",
        "service": "my-service",
        "stage": "hardening",
        "test": {
          "end": "",
          "start": ""
        }
      },
      "triggeredAt": "2022-08-24T07:59:34.473Z"
    }
```

This should be changed, so that the last task of a sequence is also moved to the `previousTasks` property, since having a `finished` sequence with a `currentTask` might be misleading to the users of the API

### PR DESCRIPTION
**Pull request by bacherfl**
This PR changes the final update of a sequence execution to update the complete item instead of just setting the `state` property to `finished`
Closes #8808

### CODE REVIEW

File: shipyard-controller/main_test.go [hunk 1]
```diff
@@ -845,8 +845,14 @@ func Test__main_SequenceStateParallelStages(t *testing.T) {
 	require.Equal(t, keptnv2.GetTriggeredEventType("delivery"), stage.LatestEvent.Type)
 
 	// get delivery.triggered event
-	deliveryTriggeredEvent := natsClient.getLatestEventOfType(*keptnContext.KeptnContext, projectName, "dev", keptnv2.GetTriggeredEventType("delivery"))
-	require.NotNil(t, deliveryTriggeredEvent)
+	var deliveryTriggeredEvent *apimodels.KeptnContextExtendedCE
```
Comment (bacherfl) [inline shipyard-controller/main_test.go:848]: technically this change is out of scope for the PR, but this assertion proved to be flaky and occasionally fail

**Review by odubajDT — APPROVED** [review]
