### PR TITLE
Enhance JMeter result message

### LINKED ISSUE #3559: Need better JMeter result other than just fail
When running JMeter and things fail there is no way right now to know why it failed. Did it fail because the testing script is not there that is configured in jmeter.conf.yaml? or is it because a too high error rate?

Right now we only see this in the sequence screen
image

I suggest that JMeter - and hopefully all other tools that handle "test" events - to add a good "message" that explains why it failed

### PR DESCRIPTION
**Pull request by mishraprafful**
**Changes**
* Added Quick DNS lookup check for service Url with a relevant message for failure
* Added message parameter to `sendTestsFinishedEvent` method

**Related Issue**
Closes #3559

### CODE REVIEW

File: jmeter-service/main.go [hunk 1]
```diff
@@ -99,6 +100,17 @@ func runTests(event cloudevents.Event, shkeptncontext string, data keptnv2.TestT
 	var res bool
 	healthCheckWorkload, err = getWorkload(jmeterconf, TestStrategy_HealthCheck)
 	if healthCheckWorkload != nil {
+
+		res , err = net.LookupIP(serviceUrl.String())
+		if err != nil {
+			msg := fmt.Sprintf("Cant reach URL %s from JMeter-Service: %s", serviceUrl, err.Error())
+			logger.Error(msg)
+			if err := sendErroredTestsFinishedEvent(shkeptncontext, event, startedAt, msg, logger); err != nil {
```
Comment (johannes-b) [inline jmeter-service/main.go:108]: Please change the function from `sendErroredTestsFinishedEvent` to `sendTestsFinishedEvent` because technically the service did not errored. It just could not reach the URL.

File: jmeter-service/main.go [hunk 2]
```diff
@@ -99,6 +100,17 @@ func runTests(event cloudevents.Event, shkeptncontext string, data keptnv2.TestT
 	var res bool
 	healthCheckWorkload, err = getWorkload(jmeterconf, TestStrategy_HealthCheck)
 	if healthCheckWorkload != nil {
+
+		res , err = net.LookupIP(serviceUrl.String())
+		if err != nil {
+			msg := fmt.Sprintf("Cant reach URL %s from JMeter-Service: %s", serviceUrl, err.Error())
```
Comment (johannes-b) [inline jmeter-service/main.go:106]: (a minor change) Can you please change the user msg to: `Jmeter-service cannot reach URL %s`

File: jmeter-service/main.go [hunk 3]
```diff
@@ -110,7 +122,8 @@ func runTests(event cloudevents.Event, shkeptncontext string, data keptnv2.TestT
 		}
 
 		if !res {
-			if err := sendTestsFinishedEvent(shkeptncontext, event, startedAt, keptnv2.ResultFailed, logger); err != nil {
+			msg := fmt.Sprintf("Workload Testing Completed")
```
Comment (johannes-b) [inline jmeter-service/main.go:125]: Please do not set the message to "Workload Testing Completed", but rather derive a meaningful message from the `runWorkload` function. See `res, err = runWorkload(serviceUrl, testInfo, healthCheckWorkload, logger)` a couple lines above.

File: jmeter-service/main.go [hunk 4]
```diff
@@ -152,14 +165,15 @@ func runTests(event cloudevents.Event, shkeptncontext string, data keptnv2.TestT
 	}
 
 	// now lets send the test finished event
+	msg := fmt.Sprintf("Workload Testing Completed")
```
Comment (johannes-b) [inline jmeter-service/main.go:168]: Same as above.

**Review by johannes-b — COMMENTED** [review]
Please my comments under consideration.

**Comment by mishraprafful** [comment]
@johannes-b Thanks a lot for the comments, I've made the relevant changes.
Please consider this for a re-review. Also, please let me know if the code coverage drop is within permissible limits.

**Review by johannes-b — APPROVED** [review]
lgtm
