### PR TITLE
#2879 delete upstream repo credentials if there was an error

### LINKED ISSUE #2879: Failed update project with invalid upstream git still stores that upstream in keptns config repo
When calling `keptn update project PROJECT --git-user=user --git-token=token --git-remote-url=remote url` with invalid parameters, e.g: invalid URL or token then the CLI correctly returns an error like this

```
Error: Update project was unsuccessful. failed to set upstream: Error executing command git push --set-upstream http://keptn:********@git.student014/keptn/student014.git master: exit status 128
fatal: unable to access 'http://git.student014/keptn/student014.git/': Could not resolve host: git.student014
```

In the above case the URL was simply wrong.

While the error message correctly indicates that the update failed it seemed though that the upstream git information was stored in keptns config repo as the Keptns Bridge shows the invalid URL

image

**Environment**
* Client OS: Linux
* Keptn Version (`keptn version`): 0.7.3
* Kubernetes Cloud Provider (e.g., GKE, AKS): EKS
* Kubernetes version (`kubectl version`): 1.17

**Affected Component**

* [ ] Docs
* [x ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Gatekeeper
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #2879 

In case there already was an upstream repository defined before updating the project with the wrong one, the previous credentials will be restored.
Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>

### CODE REVIEW

File: shipyard-controller/api/project.go [hunk 1]
```diff
@@ -307,12 +307,21 @@ func (pm *projectManager) updateProject(params *operations.CreateProjectParams)
...
 		GitRemoteURI: params.GitRemoteURL,
 		GitToken:     params.GitToken,
 		GitUser:      params.GitUser,
 		ProjectName:  *params.Name,
 	})
+
+	if errObj != nil {
+		msg := fmt.Sprintf("Could not update upstream repository of project %s: %s", *params.Name, *errObj.Message)
+
+		if delErr := pm.deleteUpstreamRepoCredentials(params); delErr != nil {
```
Comment (christian-kreuzberger-dtx) [inline shipyard-controller/api/project.go:320]: If I'm not mistaken, this will only delete the upstream repo credentials, but not restore potentially previously correct credentials.

Comment (bacherfl) [reply shipyard-controller/api/project.go:320]: true. Although that raises to question if we do currently actually support the use case of updating the upstream repo multiple times? As far as I know we have not explicitly tested that use case yet, so maybe we need a separate issue for that

Comment (christian-kreuzberger-dtx) [reply shipyard-controller/api/project.go:320]: Agreed. I'll add it to #2509 (creating integration tests for the git upstream functionality).

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM, let's give it a try.
