### PR TITLE
#2487 Use default branch of origin

### LINKED ISSUE #2487: Address the GitHub branch renaming from `master` to `main`
**Problem:**
As announced by GitHub, the `master` branch will be renamed to `main` for new GitHub repositories. However, the configuration-service still has hard-coded dependencies to the repo-name `master`. See: https://github.com/github/renaming

Users might run into the following error when creating a project:
```console
$ keptn create project sockshop --shipyard=./shipyard.yaml --git-user=$GIT_USER --git-token=$GIT_TOKEN --git-remote-url=$GIT_REMOTE_URL
Starting to create project
ID of Keptn context: 1-2-3-4
Project sockshop created
Failed to create stage dev: Could not create stage.
```

Logs of configuration-service show the following output:
```
"timestamp":"2020-10-06T17:15:39.953110713Z","logLevel":"ERROR","message":"Could not create dev branch for project sockshop"}
{"timestamp":"2020-10-06T17:15:39.953132649Z","logLevel":"ERROR","message":"Error executing command git checkout master: exit status 1\nerror: path
spec 'master' did not match any file(s) known to git\n"}
```

**Fix:**
- Change the implementation of the configuration-service to support both names: `master` and `main`

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #2487 

This PR changes the configuration service to retrieve the name of the default branch of the upstream repository (if specified).
For this purpose, the output of the following command is used:

```
$ git remote show origin
remote origin
  Fetch URL: https://github.com/my-git-repo
  Push  URL: https://github.com/my-git-repo
  HEAD branch: master
  Remote branches:
    dev        new (next fetch will store in remotes/origin)
    master     tracked
    production new (next fetch will store in remotes/origin)
    staging    new (next fetch will store in remotes/origin)
  Local branch configured for 'git pull':
    master merges with remote master
  Local ref configured for 'git push':
    master pushes to master (local out of date)
```

The line containing `HEAD branch:` will tell us the name of the default branch (e.g. `master` in most cases, or `main` in newly created GitHub repositories).

NOTE: I have added a retry mechanism for this command, because it seems like it takes a couple of seconds until GitHub updates this information even when something has been pushed to the `master` branch (when using an empty repository as an upstream repo). During my tests, I noticed that right after the first commit has been pushed to the `master` branch, the name of the `HEAD branch` was set to `(unknown)` - therefore the check for that value within the code of the `GetDefaultBranch()` func.

I have tested this fix with the following scenarios:

- No upstream repository
- Empty GitHub repository 
- Initialized GitHub repository with `main` branch as default
- Empty GitLab repo 
- Empty Bitbucket repo
- Create project without upstream; add empty GitHub repo afterwards
- Create project without upstream; add GitHub repo with `main` branch afterwards

### CODE REVIEW

File: configuration-service/common/git.go [hunk 1]
```diff
@@ -357,6 +357,38 @@ func GetResourceMetadata(project string) *models.Version {
 	return result
 }
 
+// GetDefaultBranch returns the name of the default branch of the repo
+func GetDefaultBranch(project string) (string, error) {
+	projectConfigPath := config.ConfigDir + "/" + project
+
+	credentials, err := GetCredentials(project)
```
Comment (johannes-b) [inline configuration-service/common/git.go:364]: Can we add an error handling here? `if err != nil`

File: configuration-service/handlers/service_default_resource.go [hunk 2]
```diff
@@ -38,8 +38,12 @@ func PostProjectProjectNameServiceServiceNameResourceHandlerFunc(params service_
 		return service_default_resource.NewPostProjectProjectNameServiceServiceNameResourceDefault(500).WithPayload(&models.Error{Code: 400, Message: swag.String("Could not get stages for project")})
 	}
 
+	defaultBranch, _ := common.GetDefaultBranch(params.ProjectName)
```
Comment (johannes-b) [inline configuration-service/handlers/service_default_resource.go:41]: Can we catch this error and do error handling?

File: configuration-service/handlers/service_resource.go [hunk 3]
```diff
@@ -286,7 +286,11 @@ func PutProjectProjectNameStageStageNameServiceServiceNameResourceHandlerFunc(
 	logger.Debug("Successfully updated resources")
 
 	metadata := common.GetResourceMetadata(params.ProjectName)
-	metadata.Branch = "master"
+	defaultBranch, _ := common.GetDefaultBranch(params.ProjectName)
```
Comment (johannes-b) [inline configuration-service/handlers/service_resource.go:289]: Can we catch this error and do error handling?

File: configuration-service/handlers/service_resource.go [hunk 4]
```diff
@@ -329,7 +333,11 @@ func PutProjectProjectNameStageStageNameServiceServiceNameResourceResourceURIHan
 	logger.Debug("Successfully updated resource: " + params.ResourceURI)
 
 	metadata := common.GetResourceMetadata(params.ProjectName)
-	metadata.Branch = "master"
+	defaultBranch, _ := common.GetDefaultBranch(params.ProjectName)
```
Comment (johannes-b) [inline configuration-service/handlers/service_resource.go:336]: Can we catch this error and do error handling?

**Review by johannes-b — APPROVED** [review]
lgtm
