### PR TITLE
fix(bridge): Fix no-services message and link

### LINKED ISSUE #6997: Empty project leads user to wrong "Create service" link
## Issue

When having an empty project, the environment screen leads the user in wrong directions: 
1. the `onboard service` command is not available anymore
2. the provided link goes to: https://keptn.sh/docs/0.13.x/manage/service/#onboard-a-service that is not available anymore.

image

## Fix

Instead of linking the user to the documentation, provide a reference to the built-in functionality for *creating a service*:

image

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #6997

The link now redirects to the create service page (so it's the same behavior as in the create project success notification).
On service creation, the user is redirected back to the environment page.

image

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/_components/ktb-no-service-info/ktb-no-service-info.component.ts [hunk 1]
```diff
@@ -1,26 +1,31 @@
...
 @Component({
   selector: 'ktb-no-service-info',
   templateUrl: './ktb-no-service-info.component.html',
   styleUrls: [],
 })
-export class KtbNoServiceInfoComponent implements OnInit, OnDestroy {
+export class KtbNoServiceInfoComponent implements OnDestroy {
   private unsubscribe$: Subject<void> = new Subject();
-  public isQualityGatesOnly = false;
+  public routerLink = '';
```
Comment (ermin-muratovic) [inline bridge/client/app/_components/ktb-no-service-info/ktb-no-service-info.component.ts:14]: `routerLink` sounds very generic, maybe better rename it to `servicesSettingsLink` or something similar.

**Review by ermin-muratovic — CHANGES_REQUESTED** [review]

**Review by ermin-muratovic — DISMISSED** [review]
lgtm

**Review by ermin-muratovic — APPROVED** [review]
lgtm
