### PR TITLE
fix(bridge): Show error when having problems parsing shipyard.yaml (#6592)

### LINKED ISSUE #6592: Error message: Can we improve error message on API errors due to shipyard parsing
Your issue may already be reported! Please search on the [issue tracker](https://github.com/keptn/keptn/issues) before creating a new one.

**Environment**
Any keptn installation

* Client OS (e.g., Linux, macOS, Windows): Windows
* Keptn Version (`keptn version`): 0.11.4
* Kubernetes Cloud Provider (e.g., GKE, AKS): AKS
* Kubernetes version (`kubectl version`):1.20.9

 N/A

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [x] REST API
* [ ] Webhook

**Describe the bug**
If you shipyard.yaml is not properly formatted .e.g indentiation, then you will receive and API error  "sequence tasks not iterable" message . As a result, you might have later (e.g. webhook or job-executor service) when trying to configure event subscriptions in the bridge
image

**To Reproduce**

1. Change you shipyard.yaml file and decrease the indentiation of a task or tasks under one or more sequences e.g:

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
  - name: "quality-gate"
    sequences:
      - name: evaluation
        tasks:
        - name: monaco
        - name: evaluation
      - name: simple_evaluation
        tasks:
      - name: evaluation
        triggeredAfter: "6m"
        properties:
          timeframe: "6m"      
```

Note, that the evaluation task in the simple_evaluation sequence should have indentation for this to work properly e.g.

```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
  - name: "quality-gate"
    sequences:
      - name: evaluation
        tasks:
        - name: monaco
        - name: evaluation
      - name: simple_evaluation
        tasks:
        - name: evaluation
          triggeredAfter: "6m"
          properties:
            timeframe: "6m"      
```

2. Go to Uniform
2. Click on  e.g. webhook-service
3. Click on Add subscription
3. The bridge UI will show a loading screen and the console will eventually report an HTTP 500 error
image

**Expected behavior**
Perhaps a more clear error mesasge like:

"The API cannot iterate though the tasks in your sequence : {sequence name}. Please verify that your shipyard.yaml is correct. Ensure to check indentation and format."

**Current behavior**
API error given is  "sequence tasks not iterable" and error is not handled with clear message on the UI

**Screenshots**
image
image
image

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by ermin-muratovic**
## This PR
- fixes the webhook configuration screen when having issues parsing shipyard.yaml and shows a proper error message

### Related Issues
Fixes #6592 

image

### CODE REVIEW

File: bridge/server/services/data-service.ts [hunk 1]
```diff
@@ -528,16 +528,20 @@ export class DataService {
...
+            for (const task of sequence.tasks) {
+              if (!tasks.includes(task.name)) {
+                tasks.push(task.name);
+              }
             }
           }
         }
       }
+    } catch (error) {
+      throw Error('Could not parse shipyard.yaml');
```
Comment (Kirdock) [inline bridge/server/services/data-service.ts:544]: Could you write a short test for this?

**Review by Kirdock — CHANGES_REQUESTED** [review]
Could you add some UI tests for this error?
- Test if the reload button exists on error
- Test if the reload button works (maybe check it in a way that before the reload, the response is adjusted to a valid one)

File: bridge/client/assets/default-branding/app-config.json [hunk 2]
```diff
@@ -1,6 +1,6 @@
 {
   "appTitle": "keptn",
-  "logoUrl": "assets/default-branding/logo.png",
+  "logoUrl": "assets/default-branding/logo.svg",
```
Comment (Kirdock) [inline bridge/client/assets/default-branding/app-config.json:3]: At the moment the file ends with `png`. Could you set it to `png` again

File: bridge/cypress/integration/uniform-integrations.spec.ts [hunk 3]
```diff
@@ -169,6 +169,59 @@ describe('Integrations', () => {
...
+    cy.byTestId(uniformPage.UNIFORM_INTEGRATION_TABLE_LOC).find('dt-row').eq(1).click();
+    cy.get(uniformPage.SUBSCRIPTION_EXPANDABLE_LOC)
+      .first()
+      .find('dt-expandable-panel')
+      .byTestId('addSubscriptionButton')
+      .click();
+
+    cy.wait('@tasksResult');
+    cy.wait('@tasksResult');
+    cy.wait('@tasksResult');
```
Comment (Kirdock) [inline bridge/cypress/integration/uniform-integrations.spec.ts:187]: What is the reason for waiting 3 times?

**Review by Kirdock — DISMISSED** [review]

File: bridge/client/assets/default-branding/app-config.json (hunk 2 above)
Comment (ermin-muratovic) [reply bridge/client/assets/default-branding/app-config.json]: Damn rebase. Fixed it 👍🏻

File: bridge/cypress/integration/uniform-integrations.spec.ts (hunk 3 above)
Comment (ermin-muratovic) [reply bridge/cypress/integration/uniform-integrations.spec.ts:187]: Because we still have the retry strategy for HTTP calls with status 500, and therefore the error message is shown after the result was not successful after 3 tries.

**Review by laneli — APPROVED** [review]
