### PR TITLE
fix(bridge): fixes session fixation by regenerating the session cookie after login (#4947)

### LINKED ISSUE #4947: OAuth login - Session fixation
**Affected Component**

- [ ] Bridge

**Describe the bug**

OAuth login does not provide a new session cookie. This opens up session fixation vulnerability for OAuth enabled Keptn instances. 

However, bridge already utilize signed session cookies with a secret. Further, session id candidate is a crypto random. Hence, exploiting this vulnerability is not straightforward.

**Expected behaviour**

A new session cookie must be generated and authenticate for successful logins.

### PR DESCRIPTION
**Pull request by Kavindu-Dodan**
### Related Issues

Fixes #4947

### How to test

- Enabled OAuth based login 
- Check session cookie value before the login 
- Check session cookie value after the login
- Validate that cookie value has changed

### CODE REVIEW

File: bridge/server/user/session.ts [hunk 1]
```diff
@@ -127,7 +132,7 @@ function sessionRouter(app: Express)  {
 
 export { sessionRouter };
 export { isAuthenticated };
-export { setAuthenticatedSession as sessionAuthentication };
+export { authenticateSession as authenticateSession };
```
Comment (Kirdock) [inline bridge/server/user/session.ts:135]: Remove `as authenticateSession`. Renaming is not needed if they are the same.

**Review by Kirdock — CHANGES_REQUESTED** [review]

File: bridge/server/user/session.ts (hunk 1 above)
Comment (Kavindu-Dodan) [reply bridge/server/user/session.ts:135]: Perfect thanks :)

**Review by Kirdock — APPROVED** [review]
