### PR TITLE
fix(bridge): Show the heatmap even if the SLO of an evaluation is invalid

### LINKED ISSUE #7962: Bridge: The heatmap should be shown even if there is an invalid sloFileContent
For the events, there was a bug, that the sloFileContent was not encoded correctly. Because of that, the heatmap could not be shown due to a failing `btoa` command for decoding the sloFileContent.
The bridge should show the heatmap anyway, even if there may be an evaluation with an invalid sloFileContent

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #7962

image

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts [hunk 1]
```diff
@@ -102,3 +104,29 @@ export function createDataPoints(evaluationHistory: Trace[]): IDataPoint[] {
...
+        if (evaluationData.data.evaluation.comparedEvents) {
+          evaluationData.data.evaluation.number_of_comparison_results =
+            evaluationData.data.evaluation.comparedEvents?.length;
+        } else {
+          evaluationData.data.evaluation.number_of_comparison_results = 0;
+        }
+      } catch {}
+    }
+  }
+}
```
Comment (heinzburgstaller) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:132]: I think can improve the function into two, like:
```
export function parseSloFile(evaluationTraces: Trace[]): void {
  const alreadyParsed = (trace: Trace): boolean => trace?.data?.evaluation?.sloFileContent
     && !trace.data.evaluation.sloFileContentParsed;
  const mapToEvaluation = (trace: Trace): Evaluation => {
    // Maybe checks for undefined
    return trace.data.evaluation;
  };
  evaluationTraces.filter(alreadyParsed).map(mapToEvaluation)
    .forEach(e => this.parseSloFileForEvaluation(e));
}

function parseSloFileForEvaluation(evaluation) {
  try {
    // parseYml
    // assigments
  } catch {  }
}
```

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts [hunk 2]
```diff
@@ -333,7 +331,7 @@ export class KtbEvaluationDetailsComponent implements OnInit, OnDestroy {
   public ngOnInit(): void {
     this.dataService.evaluationResults.pipe(takeUntil(this.unsubscribe$)).subscribe((results) => {
       if (this.evaluationData && results.traces?.length) {
-        this.parseSloFile(results.traces);
+        parseSloFile(results.traces);
```
Comment (heinzburgstaller) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts:334]: Please refactor to early return

**Review by heinzburgstaller — CHANGES_REQUESTED** [review]

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts (hunk 1 above)
Comment (Kirdock) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:132]: For me this will not be an improvement. One for-loop is changed to three.

Comment (heinzburgstaller) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:132]: If you look at it from a runtime perspective. Look at the code, it looks like this:
```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx {
 xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx {
   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx{
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx {
     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    }
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  }
 }
}
```
As a developer you need a long time to grasp the purpose of the function. In my opinion readability and maintainability goes before runtime, when there is no need for a fast execution. If we wanted a fast client we would write it in C, which also does too many CPU cycles compared to Assembler.

A good function should not have more than one indentation.

**Review by heinzburgstaller — APPROVED** [review]

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts [hunk 3]
```diff
@@ -102,3 +105,23 @@ export function createDataPoints(evaluationHistory: Trace[]): IDataPoint[] {
...
   return [...scores, ...sortedResults];
 }
+
+export function parseSloOfEvaluations(evaluationTraces: Trace[]): void {
+  const unparsedEvaluations = (trace: Trace): trace is Trace & { data: { evaluation: IEvaluationData } } =>
+    !!trace?.data?.evaluation?.sloFileContent && !trace.data.evaluation.sloFileContentParsed;
+
+  for (const evaluationTrace of evaluationTraces.filter(unparsedEvaluations)) {
+    parseSloFile(evaluationTrace.data.evaluation);
+  }
```
Comment (renepanzar) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:115]: Why not go with the `forEach` approach, if you're already using the `filter` method?

```suggestion
  evaluationTraces
    .filter(unparsedEvaluations)
    .forEach(evaluationTrace => parseSloFile(evaluationTrace.data.evaluation));
```

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts [hunk 4]
```diff
@@ -102,3 +105,23 @@ export function createDataPoints(evaluationHistory: Trace[]): IDataPoint[] {
     .sort((a, b) => a.yElement.localeCompare(b.yElement));
   return [...scores, ...sortedResults];
 }
+
+export function parseSloOfEvaluations(evaluationTraces: Trace[]): void {
+  const unparsedEvaluations = (trace: Trace): trace is Trace & { data: { evaluation: IEvaluationData } } =>
```
Comment (renepanzar) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:110]: This could be defined outside of the function, makes it also testable.

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts [hunk 5]
```diff
@@ -102,3 +105,23 @@ export function createDataPoints(evaluationHistory: Trace[]): IDataPoint[] {
...
+    !!trace?.data?.evaluation?.sloFileContent && !trace.data.evaluation.sloFileContentParsed;
+
+  for (const evaluationTrace of evaluationTraces.filter(unparsedEvaluations)) {
+    parseSloFile(evaluationTrace.data.evaluation);
+  }
+}
+
+function parseSloFile(evaluation: IEvaluationData): void {
+  try {
+    evaluation.sloFileContentParsed = parseYaml(atob(evaluation.sloFileContent)) as SloConfig;
```
Comment (renepanzar) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:120]: Do we actually need the parsed file content after this function? Could this be replaced with a simple `evaluation.parsed = true`?

**Review by renepanzar — CHANGES_REQUESTED** [review]
A few things could be improved, otherwise LGTM.

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts (hunk 3 above)
Comment (Kirdock) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:115]: To be honest, I just don't like the `forEach` syntax. If I need a for-loop without an index, I'll always use a for-loop instead of `forEach`.

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts (hunk 4 above)
Comment (Kirdock) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:110]: More testable only if I also export it, but why should I export something that I isn't need outside?

**Review by ermin-muratovic — APPROVED** [review]
lgtm,
please include the feedback from @renepanzar

**Review by ermin-muratovic — CHANGES_REQUESTED** [review]
lgtm,
please include the feedback from @renepanzar

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html [hunk 6]
```diff
@@ -309,7 +329,12 @@
               <span [textContent]="evaluation.number_of_missing_comparison_results"></span>
               result is not showing up in the Heatmap, because it has been either invalidated or is older.
             </span>
-            <span *ngIf="evaluation.number_of_missing_comparison_results > 1">
+            <span
+              *ngIf="
+                evaluation.number_of_missing_comparison_results !== undefined &&
+                evaluation.number_of_missing_comparison_results > 1
```
[the remark this answers is not in the document]
Comment (Kirdock) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html:335]: It is. The evaluation may not have this property and `undefined > 1` does not work and throws a compile error

[the remark this answers is not in the document]
Comment (heinzburgstaller) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.html:335]: ok

**Review by ermin-muratovic — APPROVED** [review]
lgtm

**Review by renepanzar — APPROVED** [review]
LGTM! Thanks for extracting the fixture function 👍
