### PR TITLE
fix(bridge): Update projects if dashboard is visited

### LINKED ISSUE #7942: Bridge: Dashboard does not update projects
First of all, this is not related to polling. Polling should not be here but if you visit the dashboard the projects should be updated which is currently not the case.

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #7942
Also removes one additional projects call while creating a project

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/app.component.ts [hunk 1]
```diff
@@ -11,20 +13,20 @@ declare let dT_: any;
...
+
+    combineLatest([this.route.firstChild?.data ?? of({}), keptnInfo$])
       .pipe(take(1))
-      .subscribe(() => {
-        this.dataService.loadProjects();
+      .subscribe(([data]) => {
+        if (!data.projectsHandledByComponent) {
+          this.dataService.loadProjects().subscribe();
+        }
       });
```
Comment (heinzburgstaller) [inline bridge/client/app/app.component.ts:30]: Suggestion: Get rid of double subscription
```
 combineLatest([this.route.firstChild?.data ?? of({}), keptnInfo$]).pipe(
      take(1),
      filter(([data]) => !data.projectsHandledByComponent),
      mergeMap(() => this.dataService.loadProjects()),
).subscribe();

```

File: bridge/client/app/dashboard/dashboard.component.ts [hunk 2]
```diff
@@ -11,18 +10,23 @@ import { DataService } from '../_services/data.service';
...
-      this.isQualityGatesOnly = isQualityGatesOnly;
-    });
+    this.dataService.keptnInfo
+      .pipe(
+        filter((keptnInfo) => !!keptnInfo),
+        take(1)
+      )
+      .subscribe(() => {
+        this.loadProjects();
+      });
```
Comment (heinzburgstaller) [inline bridge/client/app/dashboard/dashboard.component.ts:29]: See get rid of double subscription above

File: bridge/client/app/app.component.ts (hunk 1 above)
Comment (Kirdock) [reply bridge/client/app/app.component.ts:30]: The reason why I put the check inside the subscribe instead of the pipe was to only trigger it once, as we don't care for any changes here.
If the filter is moved into the pipe, there would be another projects call if you redirect from the dashboard to another view.

**Review by heinzburgstaller — APPROVED** [review]
