### PR TITLE
fix(cli): Provide values needed for upgrading the nats dependency

### LINKED ISSUE #7315: CLI: Upgrade from 0.13.x to 0.14.x does not configure Nats properly
When upgrading Keptn using the CLI, which internally uses the `--reuse-values`, Jetstream is not enabled on the nats cluster, because in previous versions of Keptn, the value `nats.jetstream.enabled` (which is used by the nats dependency) was set to `false` by default. Also, the image tags for nats and the prometheus metrics exporter will still have the same value as in previous versions, which will lead to incompatibilities with the configuration of the recently upgraded nats helm chart.

Therefore, we need to ensure the following values have the correct values, even when upgrading with the `--reuse-values` flag:

`control-plane.nats.nats.jetstream.enabled`
`control-plane.nats.nats.image`
`control-plane.nats.exporter`

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #7315
This PR makes sure the values provided to the nats dependency are compatible with the currently used nats helm chart. Unfortunately this meas that in this case we also need to set the image of nats and the nats metrics exporter, since those are defined via the values file of the nats helm chart, and the values that have been used by the previous version are incompatible with the current chart.

For adding unit tests, a bigger refactoring will be needed, as outlined in https://github.com/keptn/keptn/issues/6439

### CODE REVIEW

File: cli/cmd/upgrade.go [hunk 1]
```diff
@@ -325,7 +325,14 @@ func doUpgrade() error {
 	// if yes, they need to be installed separately as they have moved to their own charts
 	helmHelper := helm.NewHelper()
 
-	if err := helmHelper.UpgradeChart(keptnUpgradeChart, keptnReleaseName, keptnNamespace, nil); err != nil {
+	// fetch user-defined values of the previous Keptn installation and provide those to the upgrade command
+	// this will ensure that options such as 'apiGatewayNginx.type' will stay the same, but newly introduced values will correctly be set to their default
+	previousValues, err := helmHelper.GetValues(keptnReleaseName, keptnNamespace)
```
Comment (odubajDT) [inline cli/cmd/upgrade.go:330]: do we have a unit test for this ? If no, it is possible to add it ?

File: cli/cmd/upgrade.go [hunk 2]
```diff
@@ -325,7 +325,14 @@ func doUpgrade() error {
...
+	if err != nil {
+		return fmt.Errorf("Could not complete Keptn upgrade: %s", err.Error())
+	}
+
+	if err := helmHelper.UpgradeChart(keptnUpgradeChart, keptnReleaseName, keptnNamespace, previousValues); err != nil {
```
Comment (odubajDT) [inline cli/cmd/upgrade.go:335]: also a unit test for this ?

File: cli/cmd/upgrade.go (hunk 1 above)
Comment (bacherfl) [reply cli/cmd/upgrade.go:330]: in both cases a bigger refactoring would be needed, so we decided to create a dedicated issue for that back then: https://github.com/keptn/keptn/issues/6439

Comment (odubajDT) [reply cli/cmd/upgrade.go:330]: fine by me :)

**Review by odubajDT — APPROVED** [review]

**Review by thisthat — APPROVED** [review]
Tested locally and it works
