### PR TITLE
fix(shipyard-controller): Update registration info based on integration name/namespace

### LINKED ISSUE #7996: After upgrading to Keptn 0.16.0-next.1 all webhook subscriptions are gone
**Environment**

* Keptn Version (`keptn version`): `0.16.0-next.1`

**Describe the bug**

I did an upgrade from Keptn 0.15.x to Keptn 0.16.0-next.1 and lost all webhook subscriptions: 

image

**To Reproduce**

1. Start with Keptn 0.15.x
2. Run `kepn upgrade`
3. Check subscriptions for webhook-service

**Expected behavior**
* The list of subscriptions stays.

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #7996 

This PR removes the outdated logic that created the integration ID differently for integrations that were using the recently `integration.Subscription` property. To make sure that calls to Register() do not result in different integration IDs for updated integrations, the uniform handler will first look for existing integrations based on the integration's name and it's namespace.

### CODE REVIEW

File: shipyard-controller/handler/uniformintegrationhandler.go [hunk 1]
```diff
@@ -120,6 +118,28 @@ func (rh *UniformIntegrationHandler) Register(c *gin.Context) {
...
 	}
 
+	existingIntegrations, err := rh.uniformRepo.GetUniformIntegrations(models.GetUniformIntegrationsParams{
+		Name:      integration.Name,
+		Namespace: integration.MetaData.KubernetesMetaData.Namespace,
+	})
+
+	integrationInfo := fmt.Sprintf("name=%s, namespace=%s, hostname=%s", integration.Name, integration.MetaData.KubernetesMetaData.Namespace, integration.MetaData.Hostname)
+	logger.Debugf("Uniform:Register(): Checking for existing integration for %s", integrationInfo)
+	if err == nil && existingIntegrations != nil && len(existingIntegrations) > 0 {
```
Comment (warber) [inline shipyard-controller/handler/uniformintegrationhandler.go:128]:
```suggestion
	if err == nil && len(existingIntegrations) > 0 {
```

Comment (bacherfl) [reply shipyard-controller/handler/uniformintegrationhandler.go]: thx, updated the check

**Review by odubajDT — APPROVED** [review]

**Review by RealAnna — APPROVED** [review]
it works
