### PR TITLE
fix: Fixed automatic navigation to latest stage

### LINKED ISSUE #8684: Bridge: Navigate to current last stage when clicking on stage in ktb-root-events-list
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.18.1-dev

**Affected Component**

* [ ] Approval
* [x] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When clicking on a stage inside the `ktb-root-events-list` the UI initially navigates to the correct sequence and stage but then quickly redirects to the last stage.

**To Reproduce**

1. Go to the sequences page
2. Click on `dt-tag` inside `ktb-root-events-list`

**Expected behavior**
UI stays on selected stage after navigation

**Current behavior**
UI moves to last stage

**Screenshots**

https://user-images.githubusercontent.com/36239763/185112133-c8f6acef-1bfa-457d-ab1d-26b58eb7cbf1.mp4

Related to #8614

### PR DESCRIPTION
**Pull request by TannerGilbert**
## This PR

- Fixes automatic navigation to latest stage when clicking `dt-tag` from `ktb-root-events-list`.
- Added UI tests for navigation to correct stage.

### Related Issues

Fixes #8684

### Notes

https://user-images.githubusercontent.com/36239763/185873075-f3c2a07e-faaf-4ce3-888a-a977437bc329.mp4

Signed-off-by: TannerGilbert <gilberttanner.work@gmail.com>

### CODE REVIEW

File: bridge/cypress/support/pageobjects/SequencesPage.ts [hunk 1]
```diff
@@ -104,8 +104,13 @@ export class SequencesPage {
     return this;
   }
 
-  public selectSequence(keptnContext: string): this {
-    cy.byTestId(`keptn-root-events-list-${keptnContext}`).click();
+  public selectSequence(keptnContext: string, stage?: string): this {
+    const rootEvent = cy.byTestId(`keptn-root-events-list-${keptnContext}`);
+    if (stage) {
+      rootEvent.find('dt-tag').contains(stage).parentsUntil('ktb-stage-badge').first().click({ force: true });
```
Comment (Kirdock) [inline bridge/cypress/support/pageobjects/SequencesPage.ts:110]: Is `force: true` needed here? For me this seems like a workaround because of the "detached from DOM" error

File: bridge/cypress/integration/sequences.spec.ts [hunk 2]
```diff
@@ -412,5 +412,26 @@ describe('Sequences', () => {
...
     });
+
+    it('should select stage when clicking stage tag', () => {
+      const project = 'sockshop';
+      const stage = 'dev';
+      const keptnContext = '62cca6f3-dc54-4df6-a04c-6ffc894a4b5e';
+      sequencePage.visit(project).selectSequence(keptnContext, stage);
+
+      // Wait for loadTraces call
+      cy.wait(100);
```
Comment (Kirdock) [inline bridge/cypress/integration/sequences.spec.ts:423]: Instead of waiting for a custom time I would give the needed call an alias and wait for this one instead

**Review by Kirdock — CHANGES_REQUESTED** [review]

File: bridge/cypress/support/pageobjects/SequencesPage.ts (hunk 1 above)
Comment (TannerGilbert) [reply bridge/cypress/support/pageobjects/SequencesPage.ts]: Seems like I used `parentsUntil` instead of `parents`

**Review by Kirdock — APPROVED** [review]

**Review by heinzburgstaller — APPROVED** [review]
