### PR TITLE
fix: Handle upstream not found (#5977)

### LINKED ISSUE #5977: keptn update project with invalid/wrong git credentials results in a HTTP 500
This is with Keptn 0.10.0:

When I try to update a project with invalid credentials, I end up getting a HTTP 500, both in Bridge and in the CLI.

# To reproduce

**shipyard.yaml**
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "hardening"

```

```console
keptn create project example --shipyard=./shipyard.yaml
```

Try to upadte the project (you can use this exact same command)
```console
keptn update project example --git-user=wrong-user --git-token=wrong-token --git-remote-url=https://github.com/christian-kreuzberger-dtx/some-repo.git
```

# Current behaviour

configuration-service responds with a HTTP 500 and no proper error message

```
Starting to update project
Error: Update project was unsuccessful. failed to set upstream: <nil>
```

This also is visible in Bridge

image

configuration-service prints the following logs

```
{"timestamp":"2021-11-10T09:46:48.625422359Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project nodejs-example: failed to set upstream: \u003cnil\u003e"}
{"timestamp":"2021-11-10T09:46:56.816517369Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project nodejs-example: failed to set upstream: \u003cnil\u003e"}
{"timestamp":"2021-11-10T09:47:06.029904658Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project nodejs-example: failed to set upstream: \u003cnil\u003e"}
{"timestamp":"2021-11-10T09:47:16.110509855Z","logLevel":"ERROR","message":"Could not add upstream repository while updating project nodejs-example: failed to set upstream: \u003cnil\u003e"}
```

# Expected behaviour

* Configuration-service **must not** respond with HTTP 500. Instead, it should be some HTTP 4xx error code
* Configuration-service should respond with a proper error message (if possible, "invalid credentials", "upstream URL not found", ... - I know this depends on the `git` CLI, so it might not be possible to do that)

### PR DESCRIPTION
**Pull request by RealAnna**
Signed-off-by: RealAnna <anna.reale@dynatrace.com>

## This PR

- adds an error handling  failure in updating a git upstream as 404
### Related Issues

Fixes #5977

### CODE REVIEW

File: configuration-service/handlers/project.go [hunk 1]
```diff
@@ -120,6 +120,10 @@ func PutProjectProjectNameHandlerFunc(params project.PutProjectProjectNameParams
 					logger.Error("Authentication error detected")
 					return project.NewPostProjectDefault(http.StatusFailedDependency).WithPayload(&models.Error{Code: http.StatusFailedDependency, Message: swag.String(err.Error())})
 				}
+				if strings.Contains(err.Error(), "failed to set upstream") {
```
Comment (bacherfl) [inline configuration-service/handlers/project.go:123]: Is the "failed to set upstream" message always an indicator for a non-existing upstream URL? Otherwise we might need to adapt the `UpdateOrCreateOrigin` function to return proper errors for different failure scenarios (e.g. unknown repo URL, authentication errors, etc)

Comment (RealAnna) [reply configuration-service/handlers/project.go:123]: upstream not found covers case of unexisting URL and wrong token, however I just tested that in case of wrong user no error is returned!!!!

Comment (warber) [reply configuration-service/handlers/project.go:123]: In any case, please do not make decisions based on log or error messages. It's just too easy to break without knowing.

**Review by bacherfl — APPROVED** [review]

**Review by bacherfl — APPROVED** [review]
