### PR TITLE
fix(lighthouse-service): inconsistent behavior when SLI provider returns warning

### LINKED ISSUE #9494: Lighthouse :: Inconsistent behavior
## Goal

The lighthouse should provide consistent handling of SLI events. 

## Technical Description

Lighthose awaits SLI providers for data used to make decisions on evaluations. The handling of the get SLI event needs to be more consistent. Here we list how Lighthouse shall handle the SLI provider's different answers.

We have three types of answers for the SLI provider: 

1. Provider returns `succeeded` -> Lighthouse evaluates the SLO definition based on the SLI values
2. Provider returns `warning`
3. Provider returns `failed` -> Lighthouse, in turn, fails

In the second case, Lighthouse has to look into each SLO definition and there could be two cases:
1. The SLO has **NO** pass/warning criteria: this is an informative SLO and Lighthouse will ignore this entry and will NOT contribute to the overall score, but the SLI value is reported. This way, it gets into the Heatmap in the Bridge.
2. The SLO has pass/warning criteria. The eval of this entry will contribute to the score:
	* if the SLI indicator has success=false the SLO entry is considered failed
	* otherwise, the SLO definition is normally evaluated

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- fixes inconsistent behaviour when SLI provider returns warning

### Related Issues

Fixes #9494 

https://github.com/keptn/keptn/actions/runs/4121475886

### CODE REVIEW

File: lighthouse-service/event_handler/evaluate_sli_handler.go [hunk 1]
```diff
@@ -42,6 +42,12 @@ type criteriaObject struct {
 	CheckIncrease   bool
 }
 
+type KeySLI struct {
```
Comment (bacherfl) [inline lighthouse-service/event_handler/evaluate_sli_handler.go:45]: do we need this struct somewhere else or would it make sense to make it unexported?

Comment (odubajDT) [reply lighthouse-service/event_handler/evaluate_sli_handler.go:45]: it can be unexported, good catch!

**Review by bacherfl — APPROVED** [review]
lgtm
