### PR TITLE
ci: Disabled OOM check

### LINKED ISSUE #6810: Integration Tests: Reporting of `oom` errors gives too much false positives
After running integration tests we are capturing k8s events to see whether there were any OOM errors happening. However, the currently implemented logic seems to report too many false positives, which results in failing integration tests.
image
Also, the output lacks more detailed information about the OOM happening.

## Action Item
Let's disable the OOM check for now until we have designed/implemented a more reliable solution
The code of the currently implemented solution does not necessarily need to be deleted. It's fine to disable the section and  attach a comment.

### PR DESCRIPTION
**Pull request by RealAnna**
Signed-off-by: RealAnna <anna.reale@dynatrace.com>

## This PR
disables OOM check
fixes #6810

### CODE REVIEW

**Review by odubajDT — APPROVED** [review]

File: test/go-tests/init_test.go [hunk 1]
```diff
@@ -16,14 +16,14 @@ func TestMain(m *testing.M) {
...
 
-	events, err := GetOOMEvents()
-	if code == 0 && (len(events.Items) != 0 || err != nil) {
-		println("There were some out of memory Errors! The error messages will be printed below:")
-		for _, oomEvent := range events.Items {
-			println(oomEvent.Message)
-		}
-		os.Exit(-1)
-	}
+	//events, err := GetOOMEvents()
```
Comment (warber) [inline test/go-tests/init_test.go:19]: pls add a comment **why** this part is disabled, thx

**Review by warber — APPROVED** [review]

**Review by mowies — APPROVED** [review]
