### PR TITLE
#3027 finish task sequence when receiving event with result=fail

### LINKED ISSUE #3008: shipyard-controller: Trigger next stage regardless of evaluation result
If the evaluation of one stage does not result in `pass` (e.g. `warning`), the next stage is not triggered ([see shipyard controller](https://github.com/keptn/keptn/blob/9f5823f96f18e5a309be568be28e8c043d3cc88b/shipyard-controller/api/event.go#L604)). 

More specifically, if the task-sequence of e.g. *staging* does not have the result `pass` (qualtiy gate results in `warning`), the next task sequence in the  *production* stage is not triggered.

I would like to have the next stage triggered regardless of the evaluation result - since I have a manual approval step in the next stage. (could also be configurable if this behavior is not desired all the time)

### LINKED ISSUE #3027: Shipyard-controller stops sequence when a task returns `result=fail`
Currently, the shipyard-controller stops the orchestration of a sequence when a task returns status=errored. 

Given the following shipyard, the shipyard-controller also stops orchestrating the task sequence when `result=fail` for any task. 

```
- name: "staging"
  sequences:
  - name: "artifact-delivery"
    tasks:
    - name: "deployment"
      properties:
        deploymentstrategy: "blue_green_service"
    - name: "test"
      properties:
        teststrategy: "performance"
    - name: "evaluation"
    - name: "release"
```

**Task:**
* Change the behavior of the shipyard-controller to stop on `result=fail`
* Consider: #3008 (which can be closed afterwards)

**Definition of done:**
* [ ] A failed test will stop, e.g., the `artifact-delivery` sequence.

### LINKED ISSUE #3028: Allow filtering sequence triggers based on match properties
It should be possible to add a filter to the trigger of a sequence. The filter works on the payload of a stage event. Given the below example, the shipyard-controller would start the `rollback` sequence, when the `staging.artifact-delivery.finished` event has the property `result` set to `failed`.

```
- name: "staging"
  sequences:
  - name: "artifact-delivery"
    tasks:
    - name: "deployment"
      properties:
        deploymentstrategy: "blue_green_service"
    - name: "test"
      properties:
        teststrategy: "performance"
    - name: "evaluation"
    - name: "release"

- name: "rollback"
  on:
  - staging.artifact-delivery.finished:
    selector:
      match:
        result: failed
  tasks:
  - name: rollback
```

**Task:**
* The shipyard-controller considers the filters for kicking-off a sequence
* Write an integration test

**Definition of Done:**
* [ ] The shipyard shows the rollback sequence and the demo use-case for delivery rolls back the 0.11.2 version of carts since it failed the evaluation (failed evaluation concluded in a `staging.artifact-delivery.finished` with `result=failed`)

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #3027
Closes #3008 
Closes #3028 

Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>

### CODE REVIEW

**Review by johannes-b — APPROVED** [review]
lgtm

**Review by warber — APPROVED** [review]

File: shipyard-controller/handler/shipyardcontroller.go [hunk 1]
```diff
@@ -472,9 +451,9 @@ func (sc *shipyardController) handleTriggeredEvent(event models.Event) error {
 }
 
 func (sc *shipyardController) proceedTaskSequence(eventScope *keptnv2.EventData, taskSequence *keptnv2.Sequence, event models.Event, shipyard *keptnv2.Shipyard, previousFinishedEvents []interface{}, previousTask string) error {
-	task, err := sc.getNextTaskOfSequence(taskSequence, previousTask)
+	task, err := sc.getNextTaskOfSequence(taskSequence, previousTask, eventScope)
```
Comment (warber) [inline shipyard-controller/handler/shipyardcontroller.go:454]: can we rename the `eventScope` variable to just `eventData` in the whole file?
Also rename the `getEventScope` func to `getEventData`

File: shipyard-controller/handler/shipyardcontroller.go [hunk 2]
```diff
@@ -575,16 +551,30 @@ var errNoFurtherTaskForSequence = errors.New("no further task for sequence")
...
+				if trigger.Event == eventScope.Stage+"."+completedTaskSequence+".finished" {
+					appendSequence := false
+					// default behavior if no selector is available: 'pass', as well as 'warning' results trigger this sequence
+					if trigger.Selector.Match == nil {
+						if eventScope.Result == keptnv2.ResultPass || eventScope.Result == keptnv2.ResultWarning {
+							appendSequence = true
+						}
+					} else {
+						// if a selector is there, compare the 'result' property
+						if string(eventScope.Result) == trigger.Selector.Match["result"] {
```
Comment (warber) [inline shipyard-controller/handler/shipyardcontroller.go:568]: would it make sense to also allow matching against the other top level fields?

Comment (bacherfl) [reply shipyard-controller/handler/shipyardcontroller.go:568]: yes, but for now we agreed in https://github.com/keptn/keptn/issues/3028 to excplicitly check for `result` for now.

File: shipyard-controller/handler/shipyardcontroller.go (hunk 1 above)
Comment (bacherfl) [reply shipyard-controller/handler/shipyardcontroller.go:461]: as agreed, I have added some code comments about why it is namend `eventScope`. Naming this variable `eventScope` made more sense to me personally, because it was used to determine the current state, as well as the next action within a task sequence execution.

**Review by warber — APPROVED** [review]
