### PR TITLE
fix:  Added correct error and test to jmeter exec

### LINKED ISSUE #7359: jmeter-service: Misleading error log and problem with v0.14.1
- [x] jmeter-service v 0.14.1

### Bug

* [ ] Jmeter-service has a misleading error log: `"time="2022-04-05T07:46:16Z" level=error msg="Successfully executed JMeter test: Project: sockshop, Service: carts, Stage: dev, TestStrategy: functional, Context: a09a2033-6ef3-4151-998f-02fc6b910466"`
due do a copy-paste from the previous line: https://github.com/keptn/keptn/blob/master/jmeter-service/jmeterUtils.go#L213

* [x] jmeter-service:0.14.1 returns a failed evaluation: `time="2022-04-05T07:52:28Z" level=info msg="Sending result Project: sockshop, Service: carts, Stage: staging, TestStrategy: performance, Context: a09a2033-6ef3-4151-998f-02fc6b910466 false"` < (`false` = test result) When changing back to 0.13.4 - everything works fine.
  * Will dig deeper to get more insights here.

### Expected behavior

- [ ] Logline: Starting with "error ... " and showing the error message
- [x] jmeter-service working again.

### PR DESCRIPTION
**Pull request by RealAnna**
### Related Issues

Fixes #7359

### CODE REVIEW

File: jmeter-service/jmeterUtils.go [hunk 1]
```diff
@@ -210,9 +214,9 @@ func executeJMeter(testInfo TestInfo, workload *Workload, resultsDir string, url
 	if result && err != nil {
 		logger.Debugf("Successfully executed JMeter test: %v", testInfo)
 	} else {
-		logger.Errorf("Successfully executed JMeter test: %v", testInfo)
+		logger.Errorf("Could not parse JMeter test (%v). Error: %s  ", testInfo, err.Error())
 	}
-	return result, err
+	return result, nil
```
Comment (mowies) [inline jmeter-service/jmeterUtils.go:219]: Why do you return `nil` here? If an error actually happened, shouldn't it also be returned?
And if no error happened, `err` is `nil` anyways.

**Review by mowies — CHANGES_REQUESTED** [review]

File: jmeter-service/jmeterUtils.go (hunk 1 above)
Comment (RealAnna) [reply jmeter-service/jmeterUtils.go:219]: at that point in code err is nill but if you want I can substitute it with err

Comment (mowies) [reply jmeter-service/jmeterUtils.go:219]: But you could have an error, print the error message and then still return `nil` instead of an error object. Couldn't that be a problem?

**Review by mowies — APPROVED** [review]
