### PR TITLE
fix: URL-provisioning test should wait for pod restart

### LINKED ISSUE #7408: Integration tests failed
* Link to run: https://github.com/keptn/keptn/actions/runs/2112877739
* Triggered by: Scheduled build
* Branch: master
* Version: 0.15.0-dev.202204071245
* Datetime: 202204071245
* Commit: 787f08ba1

| Test                                                                   | GKE-1.19 | GKE-1.21 | k3s-on-GHA-v1.16.15+k3s1 | k3s-on-GHA-v1.21.1+k3s1 | minishift-on-GHA-3.11 | k3d-on-GHA-v4.4.6 |
| ---------------------------------------------------------------------- | -------- | -------- | ------------------------ | ----------------------- | --------------------- | ----------------- |
| Test_BackupRestoreConfigService                                        | :white_check_mark: pass     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_GracefulShutdown                                                  | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_LogIngestion                                                      | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_LogForwarding                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceState                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceStateParallelStages                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceState_RetrieveMultipleSequence                            | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceState_SequenceNotFound                                    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceState_InvalidShipyard                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceState_CannotRetrieveShipyard                              | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceQueue                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceQueue_TriggerMultiple                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceQueue_TriggerAndDeleteProject                             | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceLoopIntegrationTest                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SelfHealing                                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_ResourceServiceBasic                                              | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_ManageSecrets_CreateUpdateAndDeleteSecret                         | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_Webhook                                                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_Webhook_OverlappingSubscriptions                                  | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_WebhookWithDisabledFinishedEvents                                 | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_WebhookWithDisabledStartedEvents                                  | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_WebhookConfigAtProjectLevel                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_WebhookConfigAtStageLevel                                         | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_WebhookConfigAtServiceLevel                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceTimeout                                                   | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceTimeoutDelayedTask                                        | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_Abort                                             | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_AbortQueuedSequence                               | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_AbortPausedSequence                               | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_AbortPausedSequenceTaskPartiallyFinished          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_AbortPausedSequenceMultipleStages                 | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_PauseAndResume                                    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_SequenceControl_PauseAndResume_2                                  | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_ZeroDownTimeTriggerSequence                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Test_ResourceService                                                   | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_QualityGates                                                      | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_QualityGates_SLIWrongFinishedPayloadSend                          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_QualityGates_AbortedFinishedPayloadSend                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_QualityGates_ErroredFinishedPayloadSend                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_DeliveryAssistant                                                 | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_CustomUserManagedEndpointsTest                                    | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_ContinuousDelivery                                                | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_UniformRegistration_TestAPI                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_UniformRegistration_RegistrationOfKeptnIntegration                | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_UniformRegistration_RegistrationOfKeptnIntegrationMultiplePods    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_UniformRegistration_RegistrationOfKeptnIntegrationRemoteExecPlane | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_ProvisioningURL                                                   | :white_check_mark: pass     | :x: fail     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |
| Keptn Install                                                          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :white_check_mark: pass              |
| Keptn Auth                                                             | :yellow_circle: skip     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_BackupRestoreResourceService                                      | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_ResourceServiceGETCommitID                                        | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_EvaluationGitCommitID                                             | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :x: fail                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_SSHPublicKeyAuth                                                  | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| Test_ProxyAuth                                                         | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip                  | :yellow_circle: skip              |
| TestAirgappedImagesAreSetCorrectly                                     | :yellow_circle: skip     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip                  | :white_check_mark: pass              |
| Test_WebhookWithDisabledFinishedEvents#01                              | :yellow_circle: skip     | :yellow_circle: skip     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass                  | :yellow_circle: skip              |

Note: This issue was auto-generated from [integration_tests.yml](.github/workflows/integration_tests.yml)

### PR DESCRIPTION
**Pull request by RealAnna**
Fixes #7408

### How to test

https://github.com/keptn/keptn/runs/5987118021?check_suite_focus=true webhook test fails because of old master image 

CLI check also fails due to github issues

### CODE REVIEW

File: test/go-tests/testsuite_gke_test.go [hunk 1]
```diff
@@ -53,14 +53,13 @@ func Test_GKE(t *testing.T) {
 	t.Run("Test_SequenceControl_PauseAndResume_2", Test_SequenceControl_PauseAndResume_2)
 	if res, err := CompareServiceNameWithDeploymentName("configuration-service", "resource-service"); err == nil && res {
 		t.Run("Test_ResourceServiceGETCommitID", Test_ResourceServiceGETCommitID)
-		t.Run("Test_EvaluationGitCommitID", Test_EvaluationGitCommitID)
+		t.Run("Test_GitCommitID", Test_EvaluationGitCommitID)
```
Comment (bacherfl) [inline test/go-tests/testsuite_gke_test.go:56]: was this change intended?

**Review by bacherfl — APPROVED** [review]
