### PR TITLE
fix(bridge): Evaluation info misleading if failed because of key sli

### LINKED ISSUE #5900: evaluation fails with "75 < 75" because of key-sli
Using Keptn 0.10.0-next.2, I managed to create an interesting evaluation result:

image

The evaluation is failing correctly, because one of my Key-SLIs is failing (more details on that below), but the display "**75** < 75" seems to be wrong (the number in bold is the achieved score).

# Expected behaviour

I would expect the evaluation to display as "fail" because a Key SLI has failed, without comparing it to anything else. We do something similar (but in the positive direction with a "success") when no SLO file is present, e.g.:

image

# Reproducability / More details

## Step 1: Run Quickstart Step 5

I've run into this issue by following [Quickstart Step 5](https://keptn.sh/docs/quickstart/) (Perform a multi-stage delivery) on my Keptn 0.10.0-next.2:

This is the SLO file used:
```
---
spec_version: '0.1.0'
comparison:
  compare_with: "single_result"
  include_result_with_score: "pass"
  aggregate_function: avg
objectives:
  - sli: http_response_time_seconds_main_page_sum
    displayName: "HTTP Respone Time"
    pass:
      - criteria:
          - "<=0.4"
    warning:
      - criteria:
          - "<=0.1"
  - sli: request_throughput
    displayName: "Request Throughput"
    pass:
      - criteria:
          #- "<=+100%"
          - ">=-80%"
  - sli: go_routines
    displayName: "Go Routines"
    key_sli: true
    pass:
      - criteria:
          - "<=90"
  - sli: failing_request
    displayName: "Failing Requests"
    pass:
      - criteria:
          - "< 10"
total_score:
  pass: "90%"
  warning: "75%"
```

This is the CloudEvent generated (I've slimmed it down a bit for readability):
```
{
  "data": {
    "evaluation": {"comparedEvents": ["f0b7eeb0-0afe-4f0a-aa51-362eaef2ff7e"],
      "indicatorResults": [
        {
          "displayName": "HTTP Respone Time",
          "keySli": false,
          "passTargets": [
            {
              "criteria": "<=0.4",
              "targetValue": 0.4,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "http_response_time_seconds_main_page_sum",
            "success": true,
            "value": 0.20115315268094103
          },
          "warningTargets": [
            {
              "criteria": "<=0.1",
              "targetValue": 0.1,
              "violated": true
            }
          ]
        },
        {
          "displayName": "Request Throughput",
          "keySli": false,
          "passTargets": [
            {
              "criteria": ">=-80%",
              "targetValue": 0,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "request_throughput",
            "success": true,
            "value": 169.23333333333332
          },
          "warningTargets": null
        },
        {
          "displayName": "Go Routines",
          "keySli": true,
          "passTargets": [
            {
              "criteria": "<=90",
              "targetValue": 90,
              "violated": true
            }
          ],
          "score": 0,
          "status": "fail",
          "value": {
            "metric": "go_routines",
            "success": true,
            "value": 253
          },
          "warningTargets": null
        },
        {
          "displayName": "Failing Requests",
          "keySli": false,
          "passTargets": [
            {
              "criteria": "< 10",
              "targetValue": 10,
              "violated": false
            }
          ],
          "score": 1,
          "status": "pass",
          "value": {
            "metric": "failing_request",
            "success": true,
            "value": 0
          },
          "warningTargets": null
        }
      ],
      "result": "fail",
      "score": 75,
    },
    "message": "Evaluation failed since the calculated score of 75 is below the target value of 90",
    "project": "podtatohead",
    "result": "fail",
    "service": "helloservice",
    "stage": "hardening",
    "status": "succeeded"
  },
  "source": "lighthouse-service",
  "type": "sh.keptn.event.evaluation.finished",
}
```

## Step 2: Change SLO file

Furthermore, I've changed the SLO file to have

```
total_score:
  pass: "10%"
  warning: "5%"
```

which will make it even more obvious:
image

In addition, I've checked the message provided by lighthouse-service, which also seems to be wrong/misleading:

```
    "message": "Evaluation failed since the calculated score of 75 is below the target value of 10",
    "result": "fail",
```

### PR DESCRIPTION
**Pull request by ermin-muratovic**
## This PR
- adds details about key sli to evaluation details

### Related Issues
Fixes #5900 

Case: Score warning but keySli failed
image

Case: Score failed
image

### CODE REVIEW

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts [hunk 1]
```diff
@@ -43,6 +44,26 @@ export function getTotalScore(evaluation: Trace): number {
...
+  }
+}
+
+export function getScoreInfo(evaluation: IEvaluationData): string {
+  if (evaluation.score_state === 'pass') {
+    return ` >= ${evaluation.score_pass}`;
+  } else if (evaluation.score_state === 'warning') {
+    return ` >= ${evaluation.score_warning}`;
+  } else {
+    return ` < ${evaluation.score_warning ? evaluation.score_warning : evaluation.score_pass}`;
```
Comment (Kirdock) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.ts:63]: Can be reduced to ` < ${evaluation.score_warning || evaluation.score_pass}`

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts [hunk 2]
```diff
@@ -899,6 +899,10 @@ export class KtbEvaluationDetailsComponent implements OnInit, OnDestroy {
     this.heatmapChart?._update();
   }
 
+  public getSliInfo(indicatorResults: IndicatorResult[]): SliInfo {
```
Comment (Kirdock) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.component.ts:902]: a new property would be sufficient instead of a function inside a function.
```ts
public getSliInfo = getSliResultInfo;
```

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts [hunk 3]
```diff
@@ -38,6 +39,7 @@ import { DtInputModule } from '@dynatrace/barista-components/input';
     KtbSliBreakdownModule,
     MatDialogModule,
     MomentModule,
+    DtCardModule,
```
Comment (Kirdock) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts:42]: Is this module even used somewhere?

File: bridge/cypress/integration/evaluations.spec.ts [hunk 4]
```diff
@@ -42,6 +46,39 @@ describe('evaluations', () => {
...
+      statusCode: 200,
+      fixture: 'get.sockshop.service.carts.evaluations.keysli.mock.json',
+    });
+
+    cy.visit('/project/sockshop/service/carts/context/da740469-9920-4e0c-b304-0fd4b18d17c2/stage/staging');
+    cy.byTestId('keptn-service-view-service-carts').should('exist');
+    cy.get('ktb-heatmap').should('exist');
+
+    cy.byTestId('keptn-evaluation-details-scoreInfo').should('have.text', '50 < 75');
+    cy.byTestId('keptn-evaluation-details-resultInfo').should('have.text', 'Result: fail');
```
Comment (Kirdock) [inline bridge/cypress/integration/evaluations.spec.ts:71]: Could you move most of the tests inside page objects?
```ts
public assertScoreInfo(score: number, equality: '<' | '<=' | '>' | '>=', threshold: number){...}
public assertResultInfo(type: ResultType){...}
public assertKeySliInfo(type: 'passed' | 'failed'){...}
...
```

File: bridge/shared/models/trace.ts [hunk 5]
```diff
@@ -16,8 +16,10 @@ export interface IEvaluationData {
   sloFileContent: string;
   timeEnd: Date;
   timeStart: Date;
-  score_pass?: string;
-  score_warning?: string;
+  score_pass: number;
```
Comment (Kirdock) [inline bridge/shared/models/trace.ts:19]: Actually, this property does not exist initially. It's not provided by the API but by the bridge client.
Same for `score_warning`, `score_info` and `score_state`. Could you mark it as optional?

File: bridge/client/styles.scss [hunk 6]
```diff
@@ -426,7 +426,7 @@ pre.code {
   margin: 0 5px;
 }
 
-.dt-icon.event-icon {
+.dt-icon {
```
Comment (Kirdock) [inline bridge/client/styles.scss:429]: Why did you remove `.event-icon` here? This will affect a lot of components. Are you sure this does not cause any incorrect styles?

**Review by Kirdock — CHANGES_REQUESTED** [review]
Also, make sure the failing unit tests are adapted. Because you changed some parameters from string to number and added two new properties to the `SliInfo`, some unit tests are failing.

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts (hunk 3 above)
Comment (ermin-muratovic) [reply bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details.module.ts]: No, actually not. I was trying out how it would look like as cards, but actually not using it in the end.

File: bridge/cypress/integration/evaluations.spec.ts (hunk 4 above)
Comment (ermin-muratovic) [reply bridge/cypress/integration/evaluations.spec.ts]: I also reused some of the page object intercepts :)

File: bridge/client/styles.scss (hunk 6 above)
Comment (Kirdock) [reply bridge/client/styles.scss:429]: Then the `event-icon` class is useless and can be removed for all components

**Review by Kirdock — CHANGES_REQUESTED** [review]

File: bridge/client/styles.scss (hunk 6 above)
Comment (ermin-muratovic) [reply bridge/client/styles.scss:429]: That is true, I will remove it :)

File: bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.spec.ts [hunk 7]
```diff
@@ -168,6 +172,42 @@ describe('KtbEvaluationDetailsUtils', () => {
...
+    const evaluations = EvaluationsKeySliMock;
+    parseSloOfEvaluations(evaluations);
+
+    const failedEvaluationData: IEvaluationData = evaluations[0].data.evaluation!;
+    const failedScoreState = getScoreState(failedEvaluationData);
+
+    const warningEvaluationData: IEvaluationData = evaluations[1].data.evaluation!;
+    const warningScoreState = getScoreState(warningEvaluationData);
+
+    const passedEvaluationData: IEvaluationData = evaluations[2].data.evaluation!;
```
Comment (Kirdock) [inline bridge/client/app/_components/ktb-evaluation-details/ktb-evaluation-details-utils.spec.ts:185]: Could you remove all the lint warnings here? E.g. write instead
```ts
const failedEvaluationData = evaluations[0].data.evaluation as IEvaluationData
```

**Review by Kirdock — APPROVED** [review]
