### PR TITLE
#3399: added check for statistics service

### LINKED ISSUE #3399: Upgrade from 0.7.3 to 0.8.0-rc1 failed (because of statistics-service)
**Environment**

* Client OS (e.g., Linux, OSX, Windows): Linux
* Keptn Version (`keptn version`): 0.8.0-rc1
* Kubernetes Cloud Provider (e.g., GKE, AKS): GKE 1.16
* Kubernetes version (`kubectl version`): 1.16

**Affected Component**

* [ ] Docs
* [x] CLI
* [x] Kubernetes Integration
* [x] Installer
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [ ] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
I followed the upgrade guide here: https://keptn.sh/docs/0.8.x/operate/upgrade/ to upgrade from 0.7.3 to 0.8.0-rc1. Upgrade failed with the following error message: 

```
Start upgrading Helm Chart keptn in namespace keptn
Error: Could not complete Keptn upgrade: Error when installing/upgrading Helm Chart keptn in namespace keptn: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: keptn, name: statistics-service, existing_kind: /v1, Kind=Service, new_kind: /v1, Kind=Service 
For troubleshooting, please check the status of the keptn deployment by executing the following command: 

kubectl get pods -n keptn
```

Reason behind this is that I have Keptn 0.7.3 installed with statistics-service.

**To Reproduce**

1. Install Keptn 0.7.3 CLI
2. Install Keptn 0.7.3 on Kubernetes
3. Install [keptn-sandbox/statistics-service](https://github.com/keptn-sandbox/statistics-service/releases/tag/0.2.0) on Kubernetes
4. Install Keptn 0.8.0-rc1 CLI
5. Call `keptn upgrade --skip-upgrade-check`

**Expected behavior**
Upgrade should work.

**Current behavior**
Upgrade fails due to statistics service.

**Screenshots**
```console
$ keptn upgrade --skip-upgrade-check
* Warning: Your Keptn CLI version (0.8.0-rc1) and Keptn cluster version (0.7.3) don't match. This can lead to problems. Please make sure to use the same versions.
Skipping upgrade compatibility check!
Helm Chart used for Keptn upgrade: https://storage.googleapis.com/keptn-installer/keptn-0.8.0-rc1.tgz

Please confirm that the provided cluster information is correct: 
Cluster: gke_sai-research_europe-west1-b_keptn-060-internal-demo-cluster
Is this all correct? (y/n)
y
Using a file-based storage for the key because the password-store seems to be not set up.
Do you want to upgrade Keptn version 0.7.3 to 0.8.0-rc1? (y/n)
y
Start upgrading Helm Chart keptn in namespace keptn
Error: Could not complete Keptn upgrade: Error when installing/upgrading Helm Chart keptn in namespace keptn: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: namespace: keptn, name: statistics-service, existing_kind: /v1, Kind=Service, new_kind: /v1, Kind=Service 
For troubleshooting, please check the status of the keptn deployment by executing the following command: 

kubectl get pods -n keptn

```

# Workaround
delete statistics-service manually
```console
kubectl delete -f https://raw.githubusercontent.com/keptn-sandbox/statistics-service/release-0.2.0/deploy/service.yaml
```

# Possible Solution

In `keptn upgrade`, check if statistics-service is installed (outside of the helm-chart) and recommend an uninstallation.

### PR DESCRIPTION
**Pull request by warber**
fixes #3399 

Signed-off-by: warber <bernd.warmuth@dynatrace.com>

### CODE REVIEW

File: cli/pkg/kube/kube_utils.go [hunk 1]
```diff
@@ -57,3 +57,64 @@ func CheckKubeServerVersion(constraints string) error {
...
+func CheckDeploymentManagedByHelm(deploymentName string) (bool, error) {
+	errstr := "Failed to check if deployment %s is managed by Helm: %s"
+
+	type CmdResponse struct {
+		Metadata struct {
+			Labels map[string]string `json:"labels"`
+		} `json:"metadata"`
+	}
+
+	out, err := executeCommandFunc("kubectl", []string{"get", "deployments", deploymentName, "-n", "keptn", "-o", "json"})
```
Comment (christian-kreuzberger-dtx) [inline cli/pkg/kube/kube_utils.go:72]: Please make the namespace configurable, see 
```
	if err := helm.NewHelper().UpgradeChart(keptnUpgradeChart, keptnReleaseName, keptnNamespace, nil); err != nil {
```
in upgrade.go

File: cli/pkg/kube/kube_utils.go [hunk 2]
```diff
@@ -57,3 +57,64 @@ func CheckKubeServerVersion(constraints string) error {
...
+	}
+	type Item struct {
+		Metadata Metadata `json:"metadata"`
+	}
+	type CmdResponse struct {
+		Items []Item `json:"items"`
+	}
+
+	errstr := "Failed to check if deployment %s is available: %s"
+	out, err := executeCommandFunc("kubectl", []string{"get", "deployments", "-n", "keptn", "-o", "json"})
```
Comment (christian-kreuzberger-dtx) [inline cli/pkg/kube/kube_utils.go:104]: Same as above, the namespace needs to be configurable.

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]
I left some comments regarding the namespace which is dynamic when using `keptn upgrade -n my-namespace`

File: cli/cmd/upgrade.go [hunk 3]
```diff
@@ -150,12 +150,12 @@ func doUpgradePreRunCheck() error {
...
 
 	// Check if statistics service is already running and NOT deployed by helm (https://github.com/keptn/keptn/issues/3399)
-	statisticsDeploymentAvailable, err := kube.CheckDeploymentAvailable("statistics-service")
+	statisticsDeploymentAvailable, err := kube.CheckDeploymentAvailable("statistics-service", "keptn")
 	if err != nil {
 		return err
 	}
 	if statisticsDeploymentAvailable {
-		statisticsServiceManagedByHelm, err := kube.CheckDeploymentManagedByHelm("statistics-service")
+		statisticsServiceManagedByHelm, err := kube.CheckDeploymentManagedByHelm("statistics-service", "keptn")
```
Comment (christian-kreuzberger-dtx) [inline cli/cmd/upgrade.go:158]: Please use `namespace` as provided by `keptn upgrade -n my-namespace`

File: cli/cmd/upgrade.go [hunk 4]
```diff
@@ -150,12 +150,12 @@ func doUpgradePreRunCheck() error {
 	}
 
 	// Check if statistics service is already running and NOT deployed by helm (https://github.com/keptn/keptn/issues/3399)
-	statisticsDeploymentAvailable, err := kube.CheckDeploymentAvailable("statistics-service")
+	statisticsDeploymentAvailable, err := kube.CheckDeploymentAvailable("statistics-service", "keptn")
```
Comment (christian-kreuzberger-dtx) [inline cli/cmd/upgrade.go:153]: Please use `namespace` as provided by `keptn upgrade -n my-namespace`

**Review by christian-kreuzberger-dtx — APPROVED** [review]
Verified
image
LGTM
