### PR TITLE
fix(shipyard-controller): Dispatch new sequence directly only if no older sequence is waiting

### LINKED ISSUE #7767: Shipyard-controller skipped a sequence
**Environment**

* Keptn Version (`keptn version`): `0.15.0`

**Affected Component**

* [x] Shipyard-controller

**Describe the bug**

Keptn skipped a sequence even though it has an older timestamp: 

image

**To Reproduce**
* Trigger a delivery sequence multiple times. I triggered it for `carts-db` as well as `carts`:
```
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.3
keptn trigger delivery --project=sockshop --service=carts-db --image=docker.io/mongo:4.2.2 --sequence=delivery-direct
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.2
keptn trigger delivery --project=sockshop --service=carts --image=docker.io/keptnexamples/carts:0.13.1
```

**Expected behavior**
* The sequences are executed in the same order they were triggered

**Current behavior**
* For some reason, the sequence for `carts:0.13.1` was overtaken by `0.13.1`

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- dispaches new sequences directly only if no older sequence is executed (in state triggered or started) in the same stage, service and project
- refactoring the Add() method
- adding unit tests

### Related Issues

Fixes #7767

### Integration tests
https://github.com/keptn/keptn/actions/runs/2369401694

### CODE REVIEW

File: shipyard-controller/handler/sequencedispatcher.go [hunk 1]
```diff
@@ -57,30 +58,56 @@ func NewSequenceDispatcher(
...
+		return err2
+	}
+	return ErrSequenceBlockedWaiting
+}
+
+func (sd *SequenceDispatcher) isQueueEmpty(queueItem models.QueueItem) (bool, error) {
+	queuedSequences, err := sd.sequenceQueue.GetQueuedSequences()
+	if err != nil {
+		if !errors.Is(err, db.ErrNoEventFound) {
+			return false, sd.addItemToQueue(queueItem)
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:102]: calling `addItemToQueue()` within the `isQueueEmpty` seems counterintuitive - can we move that outside?

File: shipyard-controller/handler/sequencedispatcher.go [hunk 2]
```diff
@@ -57,30 +58,56 @@ func NewSequenceDispatcher(
...
-			} else if errors.Is(err, ErrSequenceBlockedWaiting) {
-				//if the sequence is currently blocked and should wait, insert it into the queue
-				if err2 := sd.add(queueItem); err2 != nil {
-					return err2
+		//so we try to dispatch the sequence immediately if the sequence queue is empty
+		queueEmpty, err := sd.isQueueEmpty(queueItem)
+		if err != nil {
+			return err
+		}
+		if queueEmpty {
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:68]: this can be made a little easier to follow by restructuring it like so:

```
if !queueEmpty {
  return sd.addItemToQueue(queueItem)
}

if err := sd.dispatchSequence(queueItem); err != nil {
 if errors.Is(err, ErrSequenceBlocked) {
 	//if the sequence is currently blocked, insert it into the queue
 	return sd.add(queueItem)
 } else if errors.Is(err, ErrSequenceBlockedWaiting) {
 	//if the sequence is currently blocked and should wait, insert it into the queue
 	return sd.addItemToQueue(queueItem)
 } else {
 	return err
 }
}
```

this way we can reduce the nesting by one layer

File: shipyard-controller/handler/sequencedispatcher.go [hunk 3]
```diff
@@ -80,7 +81,28 @@ func (sd *SequenceDispatcher) Add(queueItem models.QueueItem) error {
...
 
+func (sd *SequenceDispatcher) addItemToQueue(queueItem models.QueueItem) error {
+	if err2 := sd.add(queueItem); err2 != nil {
+		return err2
+	}
+	return ErrSequenceBlockedWaiting
+}
+
+func (sd *SequenceDispatcher) isQueueEmpty(queueItem models.QueueItem) (bool, error) {
+	queuedSequences, err := sd.sequenceQueue.GetQueuedSequences()
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:94]: would we achieve the same functionality by checking if there are SequenceExecutionStates with status `triggered` (for the same project/stage/service)? `sequenceQueue.GetQueuedSequences()` will return the complete queue, and also this means that having an item form another project in the queue will affect if a sequence will be immediately dispatched or not

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher.go:94]: sure we can try this approach

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher.go]: applied

File: shipyard-controller/handler/sequencedispatcher.go [hunk 4]
```diff
@@ -80,7 +81,13 @@ func (sd *SequenceDispatcher) Add(queueItem models.QueueItem) error {
 		//if there are multiple shipyard we should only write
 		return sd.add(queueItem)
 	}
+}
 
+func (sd *SequenceDispatcher) addItemToQueue(queueItem models.QueueItem) error {
+	if err2 := sd.add(queueItem); err2 != nil {
+		return err2
+	}
+	return ErrSequenceBlockedWaiting
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:90]: returning `ErrSequenceBlockedWaiting` seems counterintuitive at this point, as adding an item to the queue usually is already a consequence of the sequence being blocked - can we move the return of the `ErrSequenceBlockedWaiting` to the caller of this method?

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher.go:90]: Sure, we can move it there, but that will mean one more `if err != nil { return err} return ErrSequenceBlockedWaiting` in each caller place, so than it makes no sense to have a function for this few lines and we can paste them on the caller place directly

File: shipyard-controller/handler/sequencedispatcher.go [hunk 5]
```diff
@@ -147,6 +146,55 @@ func (sd *SequenceDispatcher) dispatchSequences() {
...
+				Service: queueItem.Scope.Service,
+			},
+		},
+		Status: []string{apimodels.SequenceStartedState},
+	})
+	if err != nil {
+		return true, err
+	}
+
+	if len(startedSequenceExecutions) > 0 {
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:165]: can we also add a log here to print the keptnContext ID of the currently started sequence? Retrieving the ID of the currently running sequence has often been complicated, especially in support cases where we don't have access to the DB, so this would be really helpful here :)

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher.go:165]: sure no problem :)

File: shipyard-controller/handler/sequencedispatcher_test.go [hunk 6]
```diff
@@ -357,6 +358,146 @@ func TestSequenceDispatcher_AddError(t *testing.T) {
 
 }
 
+func TestSequenceDispatcher_QueueIsNotEmpty(t *testing.T) {
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher_test.go:361]: Can we also add a test case where there are currently no sequences with state = `started`, but other queued sequences that preceed the current one?

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher_test.go:361]: such a test is there, pushed it few minutes earlier, we can have a call to explain if you want :)

File: shipyard-controller/db/mongodb_sequence_execution_repo.go [hunk 7]
```diff
@@ -348,6 +349,11 @@ func (mdbrepo *MongoDBSequenceExecutionRepo) getSearchOptions(filter models.Sequ
 	searchOptions = appendFilterAs(searchOptions, filter.Scope.Stage, "scope.stage")
 	searchOptions = appendFilterAs(searchOptions, filter.Scope.Service, "scope.service")
 	searchOptions = appendFilterAs(searchOptions, filter.CurrentTriggeredID, "status.currentTask.triggeredID")
+	if !filter.TriggeredAt.IsZero() {
```
Comment (bacherfl) [inline shipyard-controller/db/mongodb_sequence_execution_repo.go:352]: should we rather add a `From`/`To` field to the `SequenceExecutionFilter`? It might not be immediately clear that a `$lt` operator is applied if `TriggeredAt` is provided in the filter

Comment (odubajDT) [reply shipyard-controller/db/mongodb_sequence_execution_repo.go:352]: we actually want to filter always sequences which are less than the actual timestamp, I don't think `from`/`to` makes much sense here. If the `TriggeredAt` is not set, the behaviour of the filter stays unchanged and we do not need to deal with any incompatibilities. Also `from`/`to` will introduce extra logic, parameters and also slows the request when applied every time

File: shipyard-controller/handler/sequencedispatcher.go [hunk 8]
```diff
@@ -147,6 +146,61 @@ func (sd *SequenceDispatcher) dispatchSequences() {
...
+			return true, nil
+		}
+	}
+
+	if len(triggeredSequenceExecutions) > 1 {
+		log.Infof("Sequence with KeptnContext %s is blocked due to triggered sequences in stage %s", queueItem.Scope.KeptnContext, queueItem.Scope.Stage)
+		return true, nil
+	}
+
+	log.Infof("Sequence with KeptnContext %s is not blocked by any other sequence in stage %s", queueItem.Scope.KeptnContext, queueItem.Scope.Stage)
```
Comment (bacherfl) [inline shipyard-controller/handler/sequencedispatcher.go:200]: i think we can remove this log line, as this will otherwise make the logs very verbose

Comment (odubajDT) [reply shipyard-controller/handler/sequencedispatcher.go]: adapted

**Review by bacherfl — APPROVED** [review]
