### PR TITLE
ci: Ensure CI pipeline fails if helm fails

### LINKED ISSUE #7925: CI pipeline does not fail when the chart build returns error
**Describe the bug**

Build chart pipeline did not fail with helm error [here](https://github.com/keptn/keptn/runs/6665849710?check_suite_focus=true#step:3:21) 

**Expected behavior**

Red failed pipeline
**Current behavior**

The chart is built and substituted, and the resulting installation fails, in this case nats was not deployed

**Screenshots**

image

### PR DESCRIPTION
**Pull request by RealAnna**
Signed-off-by: RealAnna <anna.reale@dynatrace.com>

## This PR

Adds helm install --dry-run --debug to our helm checks

### Related Issues

Fixes #7925

### How to test

messup something visible at runtime and push :)  e.g.  in shipyard.yaml refer to value .Values.shipyardController.notexist
image
image

### CODE REVIEW

File: gh-actions-scripts/build-helm-charts.sh [hunk 1]
```diff
@@ -110,14 +140,28 @@ fi
 
 mv "jmeter-service-${VERSION}.tgz" "keptn-charts/jmeter-service-${VERSION}.tgz"
 
+echo "::group::Template of jmeter-service"
 #verify the chart
 helm template --debug "keptn-charts/jmeter-service-${VERSION}.tgz"
 
 if [ $? -ne 0 ]; then
-  echo "::error Helm Chart for jmeter-svc has templating errors -exiting"
+  echo "::error::Helm Chart for jmeter-svc has templating errors -exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:148]:
```suggestion
  echo "::error::Helm Chart for jmeter-svc has templating errors - exiting"
```

File: gh-actions-scripts/build-helm-charts.sh [hunk 2]
```diff
@@ -110,14 +140,28 @@ fi
...
 fi
+echo "::endgroup::"
+
 
+# verify the chart with install
+echo "::group::Dry run install of jmeter-service"
+helm install --dryrun "keptn-charts/jmeter-service-${VERSION}.tgz"
+
+if [ $? -ne 0 ]; then
+  echo "::error::Helm Chart for installer has runtime errors - exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:160]:
```suggestion
  echo "::error::Helm Chart for jmeter-service has runtime errors - exiting"
```

File: gh-actions-scripts/build-helm-charts.sh [hunk 3]
```diff
@@ -88,12 +104,26 @@ fi
...
   exit 1
 fi
+echo "::endgroup::"
+
+# verify the chart with install
+echo "::group::Dry run install of helm-service"
+helm install --dryrun "keptn-charts/helm-service-${VERSION}.tgz" > out.yml
+
+if [ $? -ne 0 ]; then
+  echo "::error::Helm Chart for installer has runtime errors - exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:122]:
```suggestion
  echo "::error::Helm Chart for helm-service has runtime errors - exiting"
```

File: gh-actions-scripts/build-helm-charts.sh [hunk 4]
```diff
@@ -65,13 +65,29 @@ fi
...
 fi
 
+echo "::endgroup::"
+
+# verify the chart with install
+echo "::group::Dry run install of keptn"
+helm install --dryrun "keptn-charts/keptn-${VERSION}.tgz"
+
+if [ $? -ne 0 ]; then
+  echo "::error::Helm Chart for installer has runtime errors - exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:84]:
```suggestion
  echo "::error::Helm Chart for keptn has runtime errors - exiting"
```

File: gh-actions-scripts/build-helm-charts.sh [hunk 5]
```diff
@@ -88,12 +104,26 @@ fi
 mv "helm-service-${VERSION}.tgz" "keptn-charts/helm-service-${VERSION}.tgz"
 
 #verify the chart
+echo "::group::Template of helm-service"
 helm template --debug "keptn-charts/helm-service-${VERSION}.tgz"
 
 if [ $? -ne 0 ]; then
-  echo "::error Helm Chart for helm-svc has templating errors -exiting"
+  echo "::error::Helm Chart for helm-svc has templating errors -exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:111]:
```suggestion
  echo "::error::Helm Chart for helm-service has templating errors - exiting"
```

File: gh-actions-scripts/build-helm-charts.sh [hunk 6]
```diff
@@ -110,14 +140,28 @@ fi
 
 mv "jmeter-service-${VERSION}.tgz" "keptn-charts/jmeter-service-${VERSION}.tgz"
 
+echo "::group::Template of jmeter-service"
 #verify the chart
 helm template --debug "keptn-charts/jmeter-service-${VERSION}.tgz"
 
 if [ $? -ne 0 ]; then
-  echo "::error Helm Chart for jmeter-svc has templating errors -exiting"
+  echo "::error::Helm Chart for jmeter-svc has templating errors - exiting"
```
Comment (mowies) [inline gh-actions-scripts/build-helm-charts.sh:148]:
```suggestion
  echo "::error::Helm Chart for jmeter-service has templating errors - exiting"
```

**Review by mowies — APPROVED** [review]
LGTM, just left 2 more nitpicks :)
