### PR TITLE
fix(bridge): Fix incorrect selected stage on refresh

### LINKED ISSUE #7961: Bridge: Wrong selected stage in the sequence screen on refresh
`project/${projectName}/sequence/${keptnContext}/event/${eventId}`
If you access the sequence screen with an URL that contains a sequence that is not available in the first 25 sequences and also contains an event id, the wrong/last stage is selected instead of the right one.

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #7961 
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts [hunk 1]
```diff
@@ -276,27 +277,24 @@ export class KtbSequenceViewComponent implements OnInit, OnDestroy {
...
         .subscribe(() => {
-          this.setTraces(sequence, eventId);
+          this.setTraces(sequence, eventId, stage);
         });
     } else {
-      this.setTraces(sequence, eventId);
+      this.setTraces(sequence, eventId, stage);
       this._tracesTimer = Subscription.EMPTY;
     }
   }
```
Comment (heinzburgstaller) [inline bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:292]: Can be improved to:
```
this._tracesTimer.unsubscribe();
const reload = moment().subtract(1, 'day').isBefore(sequence.time);
const setTracesObs = reload ? AppUtils.createTimer(0, this._tracesTimerInterval) : of(null);
this._tracesTimer = setTracesObs.pipe(takeUntil(this.unsubscribe$))
  .subscribe(() => this.setTraces(sequence, eventId, stage));
```

**Review by heinzburgstaller — CHANGES_REQUESTED** [review]

**Review by heinzburgstaller — APPROVED** [review]
