### PR TITLE
fix(shipyard-controller): Adapted sequence state representation for case where sequence can not be started (#5137)

### LINKED ISSUE #5137: Bridge: A failed sequence is shown as it would be running and cannot be aborted
**Environment**

* Client OS (e.g., Linux, macOS, Windows): any
* Keptn Version (`keptn version`): 0.9.0
* Kubernetes Cloud Provider (e.g., GKE, AKS): any
* Kubernetes version (`kubectl version`): any

**Affected Component**

* [ ] Docs
* [ ] CLI
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] Helm
* [ ] Istio
* [x] Bridge
* [ ] Approval
* [ ] Datastore
* [ ] REST API
* [ ] eventbroker / distributor
* [ ] jmeter

**Describe the bug**
If a sequence fails, the Bridge shows the sequence as it would be still running. That means, the Bridge shows the spinning wheel for the sequence and also the control buttons for pausing and stopping. See Screenshot:
Screen Shot 2021-09-02 at 16 50 20

**To Reproduce**
* Preparation: Delete the shipyard.yaml in Git repo
* Trigger an evaluation
* Sequence is finished with result `fail` but Bridge still shows that this sequence is running

**Expected behavior**
Sequence should be shown as failed in Keptn Bridge.

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #5137

This PR makes sure that event when a sequence cannot be started by a `<sequence>.triggered` event, the state of the failed attempt is properly reflected and can be displayed by the bridge.
The following scenarios have been handled and are covered by integration tests:

- Shipyard file could not be retrieved
- Shipyard could be retrieved, but does not have the correct version
- Valid Shipyard is available, but no matching sequence definition found

In these cases, a sequence state will be created and immediately be set to `finished`, and the `lastFailedEvent` property will be set, so the bridge can display it as a failed sequence. The resulting `<sequence>.finished` event then contains information about why it has failed in the `data.message` property.

### CODE REVIEW

File: shipyard-controller/handler/shipyardcontroller.go [hunk 1]
```diff
@@ -537,7 +542,24 @@ func (sc *shipyardController) startTaskSequence(event models.Event) error {
...
+			Result:  keptnv2.ResultFailed,
+			Message: msg,
+		}
+		finishedEvent.Data = finishedEventData
+
+		sc.onSequenceFinished(finishedEvent)
+		return sc.sendTaskSequenceFinishedEvent(&models.EventScope{
+			EventData:    finishedEventData,
+			KeptnContext: event.Shkeptncontext,
+		}, taskSequenceName, event.ID)
```
Comment (thisthat) [inline shipyard-controller/handler/shipyardcontroller.go:562]: should also this code be pushed to its own function? This way it can be shared with the one in `onTriggerSequenceFailed()`

Comment (bacherfl) [reply shipyard-controller/handler/shipyardcontroller.go]: you're right - that can be reused here as well

**Review by thisthat — APPROVED** [review]

File: shipyard-controller/handler/shipyardcontroller.go (hunk 1 above)
Comment (thisthat) [reply shipyard-controller/handler/shipyardcontroller.go]: Thank you :shipit:
