### PR TITLE
#4446, #4521 fixed error on approval if the service has not been updated since creation

### LINKED ISSUE #4446: Environment screen broken caused by JavaScript error
See the following screen. I have a three stage delivery pipeline with an open approval request but no option to approve it in this screen
image

Here is a JavaScript Error that hopefully gives more indication on the issue
image

**Environment**
keptn 0.8.4

How to reproduce -> keptn on k3s tutorial with 3 stage delivery use case.

### LINKED ISSUE #4521: Bridge throws JavaScript errors - not showing approval option until refresh
This might be related with some other JavaScript errors I have already reported. however - in my tutorials that are based on https://github.com/keptn-sandbox/keptn-on-k3s I often run into the issue that the bridge doesnt show current status until I refresh the page

Here is an example of the approval not showing the options:
image

When looking at my browser dev tools I see this
image

When I switch over to the other view I see the approval option
image

When I switch back to the sequence for or refresh the sequence view it also works as explained above
image

This is Keptn 0.8.4

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #4446 
Fixes #4521 

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/project-board/project-board.component.ts [hunk 1]
```diff
@@ -22,6 +22,7 @@ export class ProjectBoardComponent implements OnInit, OnDestroy {
   public project$: Observable<Project>;
   public contextId: string;
   private _rootEventsTimerInterval = 30;
+  private readonly _projectTimerInterval = 30_000;
```
Comment (ermin-muratovic) [inline bridge/client/app/project-board/project-board.component.ts:25]: Have never seen this syntax yet with `30_000`, but it seems to be working. Do you know of any browser restriction or is this feature supported by all "modern" browsers?

Comment (ermin-muratovic) [reply bridge/client/app/project-board/project-board.component.ts:25]: Just found out that it is not supported by IE, but Edge and of course all other desktop browsers do have this feature already implemented.
https://caniuse.com/mdn-javascript_grammar_numeric_separators

Comment (Kirdock) [reply bridge/client/app/project-board/project-board.component.ts:25]: The separators are omitted on build

Comment (ermin-muratovic) [reply bridge/client/app/project-board/project-board.component.ts:25]: Just created an issue to document supported browsers https://github.com/keptn/keptn/issues/4637
but I realized that it works, as you said because it is omitted on build.
