### PR TITLE
fix(helm-service): Handling of helm-charts loading problems

### LINKED ISSUE #7061: signal SIGSEGV: segmentation violation on helm-service
**Environment**

* Client OS (e.g., Linux, macOS, Windows): Linux
* Keptn Version (`keptn version`): 0.13.1
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift
* Kubernetes version (`kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+b93fd35", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2022-02-11T05:26:59Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**

Once helm-service is installed in a multicluster setup, after releasing the chart it always restarts because of this error:

> {"timestamp":"2022-03-03T15:18:25.775564696Z","logLevel":"INFO","message":"Starting deployment for service test-20220303-5-svc in stage svil of project test-20220303-5"}
> {"timestamp":"2022-03-03T15:18:25.784516125Z","logLevel":"INFO","message":"Updating values for service test-20220303-5-svc in stage svil of project test-20220303-5"}
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x25a83c5]
> goroutine 2495 [running]:
> github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ValuesManipulator).Manipulate(0xc000506348, 0x0, 0x13, 0x0)
>     /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/values_manipulator.go:25 +0xc5
> github.com/keptn/keptn/helm-service/pkg/configurationchanger.(*ConfigurationChanger).UpdateLoadedChart(0xc00023cc68, 0x0, 0xc000416f80, 0xf, 0xc000416f7c, 0x4, 0xc000058990, 0x13, 0x0, 0x0, ...)
>     /go/src/github.com/keptn/keptn/helm-service/pkg/configurationchanger/configuration_changer.go:34 +0xca
> github.com/keptn/keptn/helm-service/controller.(*DeploymentHandler).HandleEvent(0xc000621600, 0x2da30c0, 0xc000264d20, 0xc0000dc000, 0x173, 0x180, 0x0, 0x0)
>     /go/src/github.com/keptn/keptn/helm-service/controller/deployment_handler.go:67 +0xdc5
> main.gracefulMiddleware(0x2d786e0, 0xc0001fa000, 0x2da30c0, 0xc000264d20, 0xc0000dc000, 0x173, 0x180, 0x0, 0x0, 0x2d97448, ...)
>     /go/src/github.com/keptn/keptn/helm-service/main.go:243 +0xd1
> created by main.gotEvent
>     /go/src/github.com/keptn/keptn/helm-service/main.go:102 +0xfdc
> goroutine 1 [select, 25 minutes]:
> github.com/cloudevents/sdk-go/v2/protocol/http.(*Protocol).OpenInbound(0xc00011ed00, 0x2d78440, 0xc0001fe2c0, 0x0, 0x0)
>     /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/protocol/http/protocol_lifecycle.go:57 +0x365
> github.com/cloudevents/sdk-go/v2/client.(*ceClient).StartReceiver(0xc00011f040, 0x2d78440, 0xc0001fe280, 0x2786aa0, 0x2b80a08, 0x0, 0x0)
>     /go/pkg/mod/github.com/cloudevents/sdk-go/v2@v2.8.0/client/client.go:265 +0x458
> main._main(0xc000118200, 0x0, 0x0, 0x1f90, 0x264bf56, 0x1, 0xc00005401a, 0x4, 0xc000000180)
>     /go/src/github.com/keptn/keptn/helm-service/main.go:200 +0x388
> main.main()
>     /go/src/github.com/keptn/keptn/helm-service/main.go:62 +0x199
> goroutine 19 [chan receive]:
> k8s.io/klog/v2.(*loggingT).flushDaemon(0x3bebb00)
>     /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1169 +0x8b
> created by k8s.io/klog/v2.init.0
>     /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:420 +0xdf

After the restard, the helm-service doesn't handle anymore other sequences.

**To Reproduce**

1. Install Keptn 0.13.1 via helm chart 
2. Install helm-service 0.13.1 via helm chart
3. Trigger sequence delivery

**Expected behavior**

helm-service correctly releasing helm-charts

**Current behavior**

After the first release, the pod restarts and doesn't release any more charts.

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- adds error handling when helm charts cannot be loaded

### Related Issues

Fixes #7061

### CODE REVIEW

File: helm-service/controller/deployment_handler.go [hunk 1]
```diff
@@ -63,6 +64,11 @@ func (h *DeploymentHandler) HandleEvent(ce cloudevents.Event) {
 		valuesUpdater := configurationchanger.NewValuesManipulator(e.ConfigurationChange.Values)
 
 		userChart, _, err = h.getUserChart(e.EventData, commitID)
+		if err != nil {
+			err = fmt.Errorf("failed to load chart: %v", err)
```
Comment (thisthat) [inline helm-service/controller/deployment_handler.go:68]:
```suggestion
			err = fmt.Errorf("failed to load chart: %w", err)
```

**Review by bacherfl — APPROVED** [review]
