### PR TITLE
#3348 avoid trying to update event of unavailable project/service/stage

### LINKED ISSUE #3348: Integration Tests are failing
https://github.com/keptn/keptn/actions/runs/591246514

| Target Platform        |  Keptn Install    |  Keptn Auth  | Linking Stages   |   Quality Gates Standalone  |  Self Healing  |  Delivery Assistant  | Continuous Delivery |
| ---------------------- | ----------------- | ------------ | ---------------- | --------------------------- | -------------- | -------------------- | ------------------- |
| kubernetes/GKE 1.15 | success | success | success | success | failure | failure | success |
| kubernetes/GKE 1.17 | success | success | success | failure | failure | failure | failure |
| kubernetes/k3s-on-GHA v1.16.15+k3s1 | success | success | success | failure | failure | skipped | skipped |
| kubernetes/k3s-on-GHA v1.19.5+k3s1 | success | success | success | failure | failure | skipped | skipped |
| openshift/minishift-on-GHA 3.11 | success | success | success | skipped | failure | skipped | skipped |

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #3348
Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>

### CODE REVIEW

File: shipyard-controller/db/projects_materialized_view.go [hunk 1]
```diff
@@ -359,6 +359,8 @@ func (mv *ProjectsMaterializedView) UpdateEventOfService(event interface{}, even
 	if err != nil {
 		mv.Logger.Error("Could not update service " + eventData.Service + " in stage " + eventData.Stage + " in project " + eventData.Project + ". Could not load project: " + err.Error())
 		return err
+	} else if existingProject == nil {
+		mv.Logger.Error("Could not update service " + eventData.Service + " in stage " + eventData.Stage + " in project " + eventData.Project + ": Project not found.")
```
Comment (christian-kreuzberger-dtx) [inline shipyard-controller/db/projects_materialized_view.go:363]: should we return here?

**Review by christian-kreuzberger-dtx — CHANGES_REQUESTED** [review]

File: shipyard-controller/db/projects_materialized_view.go (hunk 1 above)
Comment (bacherfl) [reply shipyard-controller/db/projects_materialized_view.go:363]: indeed, done

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM
