### PR TITLE
fix(webhook-service): invalid conversion of eventType

### LINKED ISSUE #5953: Webhook: Add task data to error log events
## Action Item

The WebHook service should provide the `task` value as part of the [Error Log event](https://github.com/keptn/spec/blob/master/cloudevents.md#error-log) payload.

This way, it is easier to jump from the error log message to the sequence in the Bridge.
webhook-error-logs

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- fixes invalid conversion of *.started eventType to *.finished eventType

### Related Issues

Fixes #5953

### Notes

- detailed description in issue https://github.com/keptn/keptn/issues/5953

### CODE REVIEW

File: go-sdk/pkg/sdk/keptn.go [hunk 1]
```diff
@@ -163,7 +163,11 @@ func (k *Keptn) SendFinishedEvent(event KeptnEvent, result interface{}) error {
 	if err != nil {
 		return err
 	}
-	return k.send(k.createFinishedEventForTriggeredEvent(inputCE, result))
+	if strings.HasSuffix(*event.Type, ".triggered") {
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:166]: there is a function in go-utils for checking that: https://github.com/keptn/go-utils/blob/c61381f340919feafa883d216481995ef5734553/pkg/lib/v0_2_0/events.go#L267

File: go-sdk/pkg/sdk/keptn.go [hunk 2]
```diff
@@ -257,7 +261,7 @@ func (k *Keptn) createStartedEventForTriggeredEvent(triggeredEvent cloudevents.E
 	return c
 }
 
-func (k *Keptn) createFinishedEventForTriggeredEvent(triggeredEvent cloudevents.Event, eventData interface{}) cloudevents.Event {
+func (k *Keptn) createFinishedEventForTriggeredOrStartedEvent(receivedEvent cloudevents.Event, eventData interface{}, eventSuffix string) cloudevents.Event {
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:264]: the name of this method is misleading as it now actually accepts any kind of event suffix

**Review by warber — CHANGES_REQUESTED** [review]

File: go-sdk/pkg/sdk/keptn.go (hunk 2 above)
Comment (odubajDT) [reply go-sdk/pkg/sdk/keptn.go:264]: `createFinishedEventForReceivedEvent` would be a solution?

**Comment by odubajDT** [comment]
@warber made additional small changes to generalize the function a little bit more, can you please re-launch the tests? Thanks.

File: go-sdk/pkg/sdk/keptn.go [hunk 3]
```diff
@@ -268,14 +268,14 @@ func (k *Keptn) createFinishedEventForTriggeredEvent(triggeredEvent cloudevents.
 		genericEvent["result"] = "pass"
 	}
 
-	finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".triggered") + ".finished"
-	keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+	finishedEventType, _ := ReplaceEventTypeKind(receivedEvent.Type(), "finished")
```
Comment (bacherfl) [inline go-sdk/pkg/sdk/keptn.go:271]: I think we should react on possible errors returned by this function (also in the line below)

File: go-sdk/pkg/sdk/keptn.go [hunk 4]
```diff
@@ -268,14 +273,20 @@ func (k *Keptn) createFinishedEventForTriggeredEvent(triggeredEvent cloudevents.
 		genericEvent["result"] = "pass"
 	}
 
-	finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".triggered") + ".finished"
-	keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+	finishedEventType, err := keptnv2.ReplaceEventTypeKind(receivedEvent.Type(), "finished")
+	if err != nil {
+		log.Errorf("unable to create finished event: %v from %s", err, receivedEvent.Type())
```
Comment (bacherfl) [inline go-sdk/pkg/sdk/keptn.go:278]: I think at this point we should return the error and not proceed with creating the event - at least the error message suggests that. @warber what do you think?

File: go-sdk/pkg/sdk/keptn.go [hunk 5]
```diff
@@ -325,8 +377,14 @@ func (k *Keptn) createErrorFinishedEventForTriggeredEvent(event cloudevents.Even
 	commonEventData.Status = err.StatusType
 	commonEventData.Message = err.Message
 
-	finishedEventType, _ := keptnv2.ReplaceEventTypeKind(event.Type(), "finished")
-	keptnContext, _ := event.Context.GetExtension(KeptnContextCEExtension)
+	finishedEventType, err2 := keptnv2.ReplaceEventTypeKind(event.Type(), "finished")
+	if err2 != nil {
+		return *new(cloudevents.Event), fmt.Errorf("unable to create finished event: %v from %s", err2, event.Type())
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:382]: instead of creating an empty event, the method signature should shoule be changed to `*cloudenvetns.Event`. In a case of an error return `nil, err`

File: go-sdk/pkg/sdk/keptn.go [hunk 6]
```diff
@@ -178,10 +186,15 @@ func (k *Keptn) gotEvent(ctx context.Context, event cloudevents.Event) {
...
-					// no started event sent yet, so it only makes sense to Send an error log event at this point
-					if err := k.send(k.createErrorLogEventForTriggeredEvent(event, nil, &Error{Err: err, StatusType: keptnv2.StatusErrored, ResultType: keptnv2.ResultFailed})); err != nil {
-						log.Errorf("unable to Send .finished event: %v", err)
+					if errorLogEvent, err := k.createErrorLogEventForTriggeredEvent(event, nil, &Error{Err: err, StatusType: keptnv2.StatusErrored, ResultType: keptnv2.ResultFailed}); err != nil {
+						log.Errorf("gotEvent: %v", err)
 						return
+					} else {
+						// no started event sent yet, so it only makes sense to Send an error log event at this point
+						if err := k.send(*errorLogEvent); err != nil {
+							log.Errorf("unable to Send .finished event: %v", err)
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:195]:
```suggestion
							log.Errorf("unable to send .finished event: %v", err)
```

File: go-sdk/pkg/sdk/keptn.go [hunk 7]
```diff
@@ -178,10 +186,15 @@ func (k *Keptn) gotEvent(ctx context.Context, event cloudevents.Event) {
 			if handler, ok := k.taskRegistry.Contains(event.Type()); ok {
 				keptnEvent := &KeptnEvent{}
 				if err := keptnv2.Decode(&event, keptnEvent); err != nil {
-					// no started event sent yet, so it only makes sense to Send an error log event at this point
-					if err := k.send(k.createErrorLogEventForTriggeredEvent(event, nil, &Error{Err: err, StatusType: keptnv2.StatusErrored, ResultType: keptnv2.ResultFailed})); err != nil {
-						log.Errorf("unable to Send .finished event: %v", err)
+					if errorLogEvent, err := k.createErrorLogEventForTriggeredEvent(event, nil, &Error{Err: err, StatusType: keptnv2.StatusErrored, ResultType: keptnv2.ResultFailed}); err != nil {
+						log.Errorf("gotEvent: %v", err)
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:190]: please choose a better log message

File: go-sdk/pkg/sdk/keptn.go [hunk 8]
```diff
@@ -241,9 +270,15 @@ func (k *Keptn) send(event cloudevents.Event) error {
 	return nil
 }
 
-func (k *Keptn) createStartedEventForTriggeredEvent(triggeredEvent cloudevents.Event) cloudevents.Event {
-	startedEventType, _ := keptnv2.ReplaceEventTypeKind(triggeredEvent.Type(), "started")
-	keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+func (k *Keptn) createStartedEventForTriggeredEvent(triggeredEvent cloudevents.Event) (*cloudevents.Event, error) {
+	startedEventType, err := keptnv2.ReplaceEventTypeKind(triggeredEvent.Type(), "started")
+	if err != nil {
+		return nil, fmt.Errorf("unable to create finished event: %v from %s", err, triggeredEvent.Type())
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:276]:
```suggestion
		return nil, fmt.Errorf("unable to create '.started' event: %v from %s", err, triggeredEvent.Type())
```

File: go-sdk/pkg/sdk/keptn.go [hunk 9]
```diff
@@ -268,27 +303,41 @@ func (k *Keptn) createFinishedEventForTriggeredEvent(triggeredEvent cloudevents.
 		genericEvent["result"] = "pass"
 	}
 
-	finishedEventType := strings.TrimSuffix(triggeredEvent.Type(), ".triggered") + ".finished"
-	keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+	finishedEventType, err := keptnv2.ReplaceEventTypeKind(receivedEvent.Type(), "finished")
+	if err != nil {
+		return nil, fmt.Errorf("unable to create finished event: %v from %s", err, receivedEvent.Type())
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:308]:
```suggestion
		return nil, fmt.Errorf("unable to create '.finished' event: %v from %s", err, receivedEvent.Type())
```

File: go-sdk/pkg/sdk/keptn.go [hunk 10]
```diff
@@ -303,7 +352,10 @@ func (k *Keptn) createErrorLogEventForTriggeredEvent(triggeredEvent cloudevents.
 
 	errorEventData.Message = err.Message
 
-	keptnContext, _ := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+	keptnContext, err2 := triggeredEvent.Context.GetExtension(KeptnContextCEExtension)
+	if err2 != nil {
+		return nil, fmt.Errorf("unable to get extension: %v", err2)
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:357]: bad log message... 
maybe something like:
```suggestion
		return nil, fmt.Errorf("unable to get keptn context from '.triggered' event": %v", err2)
```
?

File: go-sdk/pkg/sdk/keptn.go [hunk 11]
```diff
@@ -325,8 +377,14 @@ func (k *Keptn) createErrorFinishedEventForTriggeredEvent(event cloudevents.Even
 	commonEventData.Status = err.StatusType
 	commonEventData.Message = err.Message
 
-	finishedEventType, _ := keptnv2.ReplaceEventTypeKind(event.Type(), "finished")
-	keptnContext, _ := event.Context.GetExtension(KeptnContextCEExtension)
+	finishedEventType, err2 := keptnv2.ReplaceEventTypeKind(event.Type(), "finished")
+	if err2 != nil {
+		return nil, fmt.Errorf("unable to create finished event: %v from %s", err2, event.Type())
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:382]:
```suggestion
		return nil, fmt.Errorf("unable to create '.finished' event: %v from %s", err2, event.Type())
```

File: go-sdk/pkg/sdk/keptn.go [hunk 12]
```diff
@@ -325,8 +377,14 @@ func (k *Keptn) createErrorFinishedEventForTriggeredEvent(event cloudevents.Even
...
+	}
+	keptnContext, err2 := event.Context.GetExtension(KeptnContextCEExtension)
+	if err2 != nil {
+		return nil, fmt.Errorf("unable to get extension: %v", err2)
```
Comment (warber) [inline go-sdk/pkg/sdk/keptn.go:386]: same in line 357

File: go-sdk/pkg/sdk/keptn.go [hunk 13]
```diff
@@ -196,28 +209,44 @@ func (k *Keptn) gotEvent(ctx context.Context, event cloudevents.Event) {
 
 				// only respond with .started event if the incoming event is a task.triggered event
 				if keptnv2.IsTaskEventType(event.Type()) && keptnv2.IsTriggeredEventType(event.Type()) && k.automaticEventResponse {
-					if err := k.send(k.createStartedEventForTriggeredEvent(event)); err != nil {
-						log.Errorf("unable to Send .started event: %v", err)
+					if startedEvent, err := k.createStartedEventForTriggeredEvent(event); err != nil {
```
Comment (bacherfl) [inline go-sdk/pkg/sdk/keptn.go:212]: The `else` statement is not needed here, you can change it to the following:

```go
if startedEvent, err := k.createStartedEventForTriggeredEvent(event); err != nil {
  log.WithError(err).Errorf("could not create .started event: %v", err)
  return
}
if err := k.send(*startedEvent); err != nil {
  log.Errorf("unable to Send .started event: %v", err)
  return
}
```

**Review by bacherfl — APPROVED** [review]
lgtm

**Review by warber — APPROVED** [review]
