### PR TITLE
fix(bridge): Fix incorrect SLI grouping in heatmap

### LINKED ISSUE #9131: Bridge: The heatmap has an incorrect grouping of SLIs
If there are several SLIs with the same name, the evaluation is split into multiple ones.
This is one evaluation, but it is shown as 5
image

### PR DESCRIPTION
**Pull request by Kirdock**
Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

Fixes #9131 
Also adds numeration to duplicate SLI names to the sli-breakdown

Previous: 
image

Now: 
image

### CODE REVIEW

File: bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts [hunk 1]
```diff
@@ -1,62 +1,87 @@
...
     let foundIndex;
-    while (
+    if (
       (foundIndex = dataPoints.findIndex(
         // eslint-disable-next-line @typescript-eslint/no-loop-func
-        (dt) => dt[key] === uniqueHeader && dt[compare] === compareWith
+        (dt) => dt.yElement === displayValue && dt.identifier === identifier
       )) < index &&
       foundIndex !== -1
     ) {
```
Comment (heinzburgstaller) [inline bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts:38]: Please refactor this IF. Its very complex, even though you need a lint rule exception. Always name complex IFs such as:
```ts
const condition = ...
if (condition)

or

if (checkCondition(...))
```

**Review by heinzburgstaller — CHANGES_REQUESTED** [review]

File: bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts (hunk 1 above)
Comment (Kirdock) [reply bridge/client/app/_components/ktb-heatmap/ktb-heatmap-utils.ts]: done

**Review by heinzburgstaller — APPROVED** [review]

**Review by heinzburgstaller — APPROVED** [review]
