### PR TITLE
#3841 fix keptn ugprade using wrong keptn helm version

### LINKED ISSUE #3841: keptn upgrade: getLatestKeptnRelease returns the wrong version
I just tried to upgrade from Keptn 0.8.1 to Keptn 0.8.2 (from nightly build) using the CLI, and got the following error:
```
$ keptn upgrade
* Warning: Your Keptn CLI version (0.8.2) and Keptn cluster version (0.8.1) don't match. This can lead to problems. Please make sure to use the same versions.
Error: No upgrade path exists from Keptn version 0.8.0-rc1 to 0.8.2
```

Why does it say `0.8.0-rc1` here? I have `0.8.1` installed (I double checked).

In addition, `keptn version` says this:
```
$ keptn version
* Warning: Your Keptn CLI version (0.8.2) and Keptn cluster version (0.8.1) don't match. This can lead to problems. Please make sure to use the same versions.
Keptn CLI version: 0.8.2
Keptn cluster version: 0.8.1
```

So at some point I assume that `keptn upgrade` is fetching the wrong version. A quick lookup of the function within the CLIs keptn upgrade command resulted me in debugging this function:

https://github.com/keptn/keptn/blob/12f079a83cd3dc1b817ad1ae327cd272003d63b0/cli/cmd/upgrade.go#L200-L211

Here we return a release which has the appVersion `0.8.0-rc1`.

However, calling `helm` directly does not show this version:
```
$ helm ls -n keptn
NAME 	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART      	APP VERSION
keptn	keptn    	12      	2021-04-20 11:04:43.144275757 +0200 CEST	deployed	keptn-0.8.1	0.8.1      
$ helm ls -n keptn -oyaml
- app_version: 0.8.1
  chart: keptn-0.8.1
  name: keptn
  namespace: keptn
  revision: "12"
  status: deployed
  updated: 2021-04-20 11:04:43.144275757 +0200 CEST
```

### PR DESCRIPTION
**Pull request by christian-kreuzberger-dtx**
Fixes #3841

Basically I added a for loop that iterates over all helm releases from the history, and choose the one that has status deployed.

### CODE REVIEW

**Review by mowies — APPROVED** [review]
LGTM 👍

File: cli/cmd/upgrade.go [hunk 1]
```diff
@@ -207,7 +207,15 @@ func getLatestKeptnRelease() (*release.Release, error) {
 		return nil, fmt.Errorf("No Keptn release found in namespace %s: %v", keptnNamespace, err)
 	}
 
-	return releases[len(releases)-1], nil
+	// iterate over releases and find the one with status = deployed
+	for _, release := range releases {
+		if release.Info.Status == "deployed" {
```
Comment (bacherfl) [inline cli/cmd/upgrade.go:212]: `"deployed"` could be replaced with `release.StatusDeployed`

Comment (christian-kreuzberger-dtx) [reply cli/cmd/upgrade.go]: Done

**Review by bacherfl — APPROVED** [review]
