### PR TITLE
fix(distributor): Sanitized logs and cleaned up forwarder lifecycle

### LINKED ISSUE #6007: Distributor: Sanitize logging
The distributor spurously outputs the following error log:
> time="2021-11-15T14:16:56Z" level=error msg="No external API endpoint defined. Forwarding directly to NATS server"

which is clearly no error.

## Action Item
Go over the current code base of the distributor and check for incorrect logging (formatting, log level, ...)

### PR DESCRIPTION
**Pull request by warber**
closes #6007 
This PR contains:
* cleaned up logging
* detangling of weird Forwarder::Start logic with graceful shutdown

Integration Test Run: https://github.com/keptn/keptn/actions/runs/1471867743

### CODE REVIEW

File: distributor/pkg/lib/events/forwarder.go [hunk 1]
```diff
@@ -33,39 +32,34 @@ func NewForwarder(httpClient *http.Client) *Forwarder {
...
 	mux.Handle(config.Global.APIProxyPath, http.HandlerFunc(f.apiProxyHandler))
+	serverURL := fmt.Sprintf("localhost:%d", config.Global.APIProxyPort)
 
 	svr := &http.Server{
 		Addr:    serverURL,
 		Handler: mux,
 	}
+
 	go func() {
+		defer ctx.Wg.Done()
```
Comment (thisthat) [inline distributor/pkg/lib/events/forwarder.go:48]: is this safe? Before, the `waitgroup.Done()` was occurring after `<-ctx.Done()`

File: distributor/pkg/lib/events/nats_connection_handler.go [hunk 2]
```diff
@@ -51,7 +51,7 @@ func (nch *NatsConnectionHandler) Connect() error {
 // RemoveAllSubscriptions removes all current subscriptions from the NATS handler
 func (nch *NatsConnectionHandler) RemoveAllSubscriptions() error {
 	if nch.natsConnection == nil || !nch.natsConnection.IsConnected() {
-		return fmt.Errorf("unable to remove all subscriptions, because not connected to NATS")
+		return fmt.Errorf("could not remove all subscriptions, because not connected to NATS")
```
Comment (thisthat) [inline distributor/pkg/lib/events/nats_connection_handler.go:54]:
```suggestion
		return fmt.Errorf("Could not remove all subscriptions, because not connected to NATS")
```

File: distributor/pkg/lib/events/nats_connection_handler.go [hunk 3]
```diff
@@ -74,18 +74,18 @@ func (nch *NatsConnectionHandler) QueueSubscribeToTopics(topics []string, queueG
 	nch.mux.Lock()
 	defer nch.mux.Unlock()
 	if nch.natsConnection == nil || !nch.natsConnection.IsConnected() {
-		return errors.New("unable to remove all subscriptions, because not connected to NATS")
+		return errors.New("could not remove all subscriptions, because not connected to NATS")
```
Comment (thisthat) [inline distributor/pkg/lib/events/nats_connection_handler.go:77]:
```suggestion
		return errors.New("Could not remove all subscriptions, because not connected to NATS")
```

Comment (thisthat) [reply distributor/pkg/lib/events/nats_connection_handler.go:77]: Why few lines above is `fmt` and here `errors`?

File: distributor/pkg/lib/events/nats_connection_handler.go [hunk 4]
```diff
@@ -74,18 +74,18 @@ func (nch *NatsConnectionHandler) QueueSubscribeToTopics(topics []string, queueG
...
 	}
 
 	if len(topics) > 0 && !IsEqual(nch.topics, topics) {
 		err := nch.RemoveAllSubscriptions()
 		if err != nil {
-			return fmt.Errorf("unable to remove all subscriptions: %w", err)
+			return fmt.Errorf("could not remove all subscriptions: %w", err)
```
Comment (thisthat) [inline distributor/pkg/lib/events/nats_connection_handler.go:83]:
```suggestion
			return fmt.Errorf("Could not remove all subscriptions: %w", err)
```

File: distributor/pkg/lib/events/poller.go [hunk 5]
```diff
@@ -44,7 +44,7 @@ func NewPoller(envConfig config.EnvConfig, eventSender EventSender, httpClient *
 
 func (p *Poller) Start(ctx *ExecutionContext) error {
 	if p.env.PubSubRecipient == "" {
-		return errors.New("unable to start NatsEventReceiver: no pubsub recipient defined")
+		return errors.New("could not start NatsEventReceiver: no pubsub recipient defined")
```
Comment (thisthat) [inline distributor/pkg/lib/events/poller.go:47]:
```suggestion
		return errors.New("Could not start NatsEventReceiver: no pubsub recipient defined")
```

File: distributor/pkg/lib/events/receiver.go [hunk 6]
```diff
@@ -48,16 +48,16 @@ func NewNATSEventReceiver(env config.EnvConfig, eventSender EventSender) *NATSEv
 
 func (n *NATSEventReceiver) Start(ctx *ExecutionContext) error {
 	if n.env.PubSubRecipient == "" {
-		return errors.New("unable to start NatsEventReceiver: no pubsub recipient defined")
+		return errors.New("could not start NatsEventReceiver: no pubsub recipient defined")
```
Comment (thisthat) [inline distributor/pkg/lib/events/receiver.go:51]:
```suggestion
		return errors.New("Could not start NatsEventReceiver: no pubsub recipient defined")
```

File: distributor/pkg/lib/events/receiver.go [hunk 7]
```diff
@@ -48,16 +48,16 @@ func NewNATSEventReceiver(env config.EnvConfig, eventSender EventSender) *NATSEv
...
 	}
 
 	if err := n.natsConnectionHandler.Connect(); err != nil {
-		return fmt.Errorf("unable to Start NatsEventReceiver: %w", err)
+		return fmt.Errorf("could not Start NatsEventReceiver: %w", err)
```
Comment (thisthat) [inline distributor/pkg/lib/events/receiver.go:55]:
```suggestion
		return fmt.Errorf("Could not Start NatsEventReceiver: %w", err)
```

File: distributor/pkg/lib/events/receiver.go [hunk 8]
```diff
@@ -48,16 +48,16 @@ func NewNATSEventReceiver(env config.EnvConfig, eventSender EventSender) *NATSEv
...
 	}
 	n.natsConnectionHandler.messageHandler = n.handleMessage
 	err := n.natsConnectionHandler.QueueSubscribeToTopics(n.env.GetPubSubTopics(), n.env.PubSubGroup)
 	if err != nil {
-		return fmt.Errorf("unable to subscribe to events: %w", err)
+		return fmt.Errorf("could not subscribe to events: %w", err)
```
Comment (thisthat) [inline distributor/pkg/lib/events/receiver.go:60]:
```suggestion
		return fmt.Errorf("Could not subscribe to events: %w", err)
```

File: distributor/pkg/lib/events/uniformwatch.go [hunk 9]
```diff
@@ -27,12 +27,12 @@ func NewUniformWatch(controlPlane controlplane.IControlPlane) *UniformWatch {
...
 
 func (sw *UniformWatch) Start(ctx context.Context) string {
-	logger.Infof("Registering Keptn Intgration")
+	logger.Info("Registering Keptn Intgration")
 	var id string
 	_ = retry.Retry(func() error {
 		integrationID, err := sw.controlPlane.Register()
 		if err != nil {
-			logger.Warnf("Unable to register to Keptn's control plane: %s", err.Error())
+			logger.Warnf("Could notregister to Keptn's control plane: %v", err)
```
Comment (thisthat) [inline distributor/pkg/lib/events/uniformwatch.go:35]:
```suggestion
			logger.Warnf("Could not register to Keptn's control plane: %v", err)
```

File: distributor/pkg/lib/events/forwarder.go (hunk 1 above)
Comment (warber) [reply distributor/pkg/lib/events/forwarder.go]: should be safe, yes. However, I encountered somethings to make graceful shutdown yet cleaner, pls take a look at the updated PR

**Review by thisthat — APPROVED** [review]

File: distributor/pkg/lib/events/forwarder.go (hunk 1 above)
Comment (thisthat) [reply distributor/pkg/lib/events/forwarder.go]: LGTM! Thank you :shipit:
