### PR TITLE
#2980 fixed port retrieval, added unit tests

### LINKED ISSUE #2980: Regression - Integration Tests for cont.delivery fails: could not determine deployment URIs: deployed service does not contain a valid port definition
On master branch from 2021-01-22: When deploying carts-db from our examples repository, the deployment fails with the following error message:
**could not determine deployment URIs: deployed service does not contain a valid port definition**

helm-service log
```
{"timestamp":"2021-01-25T10:27:18.325156055Z","logLevel":"DEBUG","message":"Got event of type sh.keptn.event.service.create.finished"}
{"timestamp":"2021-01-25T10:27:18.347077638Z","logLevel":"DEBUG","message":"Create new namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:18.358999582Z","logLevel":"DEBUG","message":"Create new namespace sockshop-staging"}
{"timestamp":"2021-01-25T10:27:18.37521319Z","logLevel":"DEBUG","message":"Create new namespace sockshop-production"}
{"timestamp":"2021-01-25T10:27:18.388205503Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage dev"}
{"timestamp":"2021-01-25T10:27:18.46784089Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage staging"}
{"timestamp":"2021-01-25T10:27:18.543163324Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage production"}
{"timestamp":"2021-01-25T10:27:27.374600763Z","logLevel":"DEBUG","message":"Got event of type sh.keptn.event.service.create.finished"}
{"timestamp":"2021-01-25T10:27:27.387716501Z","logLevel":"DEBUG","message":"Reuse existing namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:27.391744526Z","logLevel":"DEBUG","message":"Reuse existing namespace sockshop-staging"}
{"timestamp":"2021-01-25T10:27:27.395902503Z","logLevel":"DEBUG","message":"Reuse existing namespace sockshop-production"}
{"timestamp":"2021-01-25T10:27:27.398833435Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage dev"}
{"timestamp":"2021-01-25T10:27:27.44615423Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage staging"}
{"timestamp":"2021-01-25T10:27:27.501602Z","logLevel":"DEBUG","message":"Storing the Helm Chart provided by the user in stage production"}
{"timestamp":"2021-01-25T10:27:32.825915142Z","logLevel":"DEBUG","message":"Got event of type sh.keptn.event.deployment.triggered"}
{"timestamp":"2021-01-25T10:27:32.826118919Z","logLevel":"INFO","message":"Starting deployment for service carts-db in stage dev of project sockshop"}
{"timestamp":"2021-01-25T10:27:32.829492881Z","logLevel":"INFO","message":"Updating values for service carts-db in stage dev of project sockshop"}
{"timestamp":"2021-01-25T10:27:32.982633429Z","logLevel":"INFO","message":"Start upgrading release sockshop-dev-carts-db in namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:57.516596233Z","logLevel":"DEBUG","message":"---\n# Source: carts-db/templates/carts-db-deployment.yaml\napiVersion: v1\nkind: PersistentVolumeClaim\nmetadata:\n  name: carts-db-mongodata\nspec:\n  accessModes:\n  - ReadWriteOnce\n  resources:\n    requests:\n      storage: 1Gi\nstatus: {}\n---\n# Source: carts-db/templates/carts-db-service.yaml\napiVersion: v1\nkind: Service\nmetadata:\n  name: carts-db\nspec:\n  ports:\n  - name: carts-db\n    port: 27017\n    targetPort: 27017\n  selector:\n    app: carts-db\n---\n# Source: carts-db/templates/carts-db-deployment.yaml\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: carts-db\n  labels:\n    app: carts-db\nspec:\n  replicas: 1\n  strategy:\n    type: Recreate\n  selector:\n    matchLabels:\n      app: carts-db\n  template:\n    metadata:\n      labels:\n        app: carts-db\n        deployment: carts-db\n        app.kubernetes.io/name: carts-db\n        app.kubernetes.io/instance: \"carts-db-direct\"\n        app.kubernetes.io/component: database\n        app.kubernetes.io/part-of: \"sockshop\"\n        app.kubernetes.io/managed-by: Keptn\n        app.kubernetes.io/version: 4.2.2          \n    spec:\n      containers:\n      - name: carts-db \n        image: docker.io/mongo:4.2.2\n        imagePullPolicy: IfNotPresent\n        ports:\n        - containerPort: 27017\n        resources: {}\n        volumeMounts:\n        - mountPath: /data/db\n          name: carts-db-mongodata\n      restartPolicy: Always\n      volumes:\n      - name: carts-db-mongodata\n        persistentVolumeClaim:\n          claimName: carts-db-mongodata\n"}
{"timestamp":"2021-01-25T10:27:57.519728309Z","logLevel":"INFO","message":"Finished upgrading chart sockshop-dev-carts-db in namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:57.548744406Z","logLevel":"DEBUG","message":"Generating the Keptn-managed Helm Chart carts-db-generated for stage dev"}
{"timestamp":"2021-01-25T10:27:57.548769335Z","logLevel":"DEBUG","message":"For service carts-db in stage dev with deployment strategy direct, a mesh chart is generated"}
{"timestamp":"2021-01-25T10:27:57.550114362Z","logLevel":"DEBUG","message":"Storing the Keptn-generated Helm Chart carts-db-generated for stage dev"}
{"timestamp":"2021-01-25T10:27:57.593699475Z","logLevel":"INFO","message":"Start upgrading release sockshop-dev-carts-db-generated in namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:59.987415605Z","logLevel":"DEBUG","message":"---\n# Source: carts-db-generated/templates/carts-db-istio-destinationrule.yaml\napiVersion: networking.istio.io/v1alpha3\nkind: DestinationRule\nmetadata:\n  creationTimestamp: null\n  name: carts-db\nspec:\n  host: carts-db.sockshop-dev.svc.cluster.local\n---\n# Source: carts-db-generated/templates/carts-db-istio-virtualservice.yaml\napiVersion: networking.istio.io/v1alpha3\nkind: VirtualService\nmetadata:\n  creationTimestamp: null\n  name: carts-db\nspec:\n  gateways:\n  - public-gateway.istio-system\n  - mesh\n  hosts:\n  - carts-db.sockshop-dev.35.198.167.23.nip.io\n  - carts-db\n  http:\n  - route:\n    - destination:\n        host: carts-db.sockshop-dev.svc.cluster.local\n"}
{"timestamp":"2021-01-25T10:27:59.987824263Z","logLevel":"INFO","message":"Finished upgrading chart sockshop-dev-carts-db-generated in namespace sockshop-dev"}
{"timestamp":"2021-01-25T10:27:59.995617088Z","logLevel":"ERROR","message":"could not determine deployment URIs: deployed service does not contain a valid port definition"}

```

# Definition of done

- [ ] Deployment of carts-db is possible again

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #2980

Signed-off-by: Florian Bacher <florian.bacher@dynatrace.com>

### CODE REVIEW

File: helm-service/controller/deployment_handler.go [hunk 1]
```diff
@@ -190,6 +183,27 @@ func (h *DeploymentHandler) getDeploymentURIs(e keptnv2.EventData) ([]string, []
...
+	}
+	// if no port explicitly marked as TCP port could be found, take the lowest port number of all specified ports
+	if !foundPort {
+		for _, port := range service.Spec.Ports {
+			if port.Port < lowestPort {
+				lowestPort = port.Port
+				foundPort = true
+			}
+		}
+	}
```
Comment (christian-kreuzberger-dtx) [inline helm-service/controller/deployment_handler.go:203]: I guess this is because of this definition in the carts-db service?
https://github.com/keptn/examples/blob/8c8334de4ca74e5977ba3ec5d1defa1644db3f58/onboarding-carts/carts-db/templates/carts-db-service.yaml#L6-L12
(vs. this in carts https://github.com/keptn/examples/blob/8c8334de4ca74e5977ba3ec5d1defa1644db3f58/onboarding-carts/carts/templates/service.yaml#L8-L12 )

Comment (bacherfl) [reply helm-service/controller/deployment_handler.go:203]: exactly - in the carts-db, no protocol is specified for the service. Therefore I changed the logic to preferably use a port that has been declared as a TCP port, if available. If no such port is found, the restriction of checking the protocol is removed and the lowest available port is used.
