### PR TITLE
fix(bridge): Fix navigation to blocking sequence

### LINKED ISSUE #9199: Bridge: Navigate to blocking sequence does not work
If the selected waiting sequence does not have any stages (sequence-state `stages` is empty), the "go to blocking sequence"-call may fail because the blocking stage is not the first available one.

In this case the blocking stage was prod but the request was filtered for staging, because it is the first one in the shipyard file.

image

### PR DESCRIPTION
**Pull request by Kirdock**
Fixes #9199
Also fixes another bug that the "go to blocking sequence" button did not work immediately (two clicks needed) if the blocking sequence was not initially loaded.

Signed-off-by: Klaus Strießnig <k.striessnig@gmail.com>

### CODE REVIEW

File: bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts [hunk 1]
```diff
@@ -423,12 +422,30 @@ export class KtbSequenceViewComponent implements OnDestroy {
...
+    if (lastEventStage) {
+      const lastIndex = stages.indexOf(lastEventStage);
+      // if the stage is finished it would be in sequence.stages therefore we don't need to check if the stage is actually not finished
+      if (lastIndex !== -1) {
+        return lastIndex;
+      }
+      return lastIndex + 1;
+    }
+
+    return 0;
```
Comment (heinzburgstaller) [inline bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:441]: Please improve by "early return", no nested IFs

File: bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts [hunk 2]
```diff
@@ -456,7 +473,15 @@ export class KtbSequenceViewComponent implements OnDestroy {
...
-          this.dataService.loadUntilRoot(sequenceExecution.scope.project, sequenceExecution.scope.keptnContext);
+          this.dataService
+            .loadUntilRoot(sequenceExecution.scope.project, sequenceExecution.scope.keptnContext)
+            .subscribe((sequences) => {
+              const newSequence = sequences.find((seq) => seq.shkeptncontext === sequenceExecution.scope.keptnContext);
+              if (newSequence) {
+                this.selectSequence({ sequence: newSequence });
+                this.loadTraces(newSequence, undefined, sequenceExecution.scope.stage);
+              }
+            });
```
Comment (heinzburgstaller) [inline bridge/client/app/_views/ktb-sequence-view/ktb-sequence-view.component.ts:484]: There should be a way to get rid of the double subscribe? By chaining with RXJS operators...

**Review by heinzburgstaller — CHANGES_REQUESTED** [review]

**Review by heinzburgstaller — APPROVED** [review]
