### PR TITLE
fix(resource-service): Determine default branch from helm value when repository is not initialized

### LINKED ISSUE #8816: Upstream git repository is initialized with branch master instead of main
**Environment**

* Client OS (e.g., Linux, macOS, Windows): `macOS`
* Keptn Version (`keptn version`): `0.18.2`
* Kubernetes Cloud Provider (e.g., GKE, AKS): OpenShift On-Premise
* Kubernetes version (`kubectl version`): `v1.23.5`
* Upstream git repository: self-hosted GitHub Enterprise v3.4.0

**Affected Component**

* [ ] Approval
* [ ] Bridge
* [ ] CLI
* [ ] Datastore
* [ ] Docs
* [ ] Distributor / Event Broker
* [ ] Helm
* [ ] Istio
* [ ] Jmeter
* [ ] Kubernetes Integration
* [ ] Openshift Integration
* [ ] REST API
* [ ] Webhook

**Describe the bug**
When a project is created on Keptn, indicating a Git repository that has not been initialized, the resulting Git repository will contain the `master` branch instead of the `main` branch

**To Reproduce**

1. Head to GitHub
2. Create a new repository
3. Choose a repository name
4. Do **not** check the "Initialize this repository with README / .gitignore" options
5. Head to Keptn
6. Create a new project
7. Choose a project name
8. Insert the link of the GitHub repository created in the previous steps
9. Insert Git user and Token
10. Choose a Shipyard file, i used the following: 
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard"
spec:
  stages:
    - name: "prod"
```
11. Head to the link of the GitHub repository created in the previous steps
12. The `master` appears in the branch list

**Expected behavior**
Once the project is created on Keptn, the upstream Git repository should contain the `main` branch

**Current behavior**
Once the project is created on Keptn, the upstream Git repository contains the `master` branch

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by odubajDT**
Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- determines default branch from helm value when repository is not initialized

### Related Issues

Fixes #8816 

### Integration tests
https://github.com/keptn/keptn/actions/runs/3037958482
https://github.com/keptn/keptn/actions/runs/3044820772

### CODE REVIEW

File: resource-service/common/git.go [hunk 1]
```diff
@@ -135,12 +140,42 @@ func (g Git) storeDefaultBranchConfig(gitContext common_models.GitContext, err e
...
+	if env.DefaultRemoteGitRepositoryBranch == "" {
+		logger.Errorf("Could not determine default remote git repository branch from env variable")
+		return "master"
+	}
+	return env.DefaultRemoteGitRepositoryBranch
+}
+
+func (g Git) rewriteDefaultBranch(path string, env envconfig.EnvConfig) error {
+	defaultBranch := retrieveDefaultBranchFromEnv(env)
+	if defaultBranch != "master" {
```
Comment (bacherfl) [inline resource-service/common/git.go:153]: let's use a constant for "master"

File: resource-service/common/git.go [hunk 2]
```diff
@@ -135,12 +140,42 @@ func (g Git) storeDefaultBranchConfig(gitContext common_models.GitContext, err e
 	return nil
 }
 
+func retrieveDefaultBranchFromEnv(env envconfig.EnvConfig) string {
+	if env.DefaultRemoteGitRepositoryBranch == "" {
+		logger.Errorf("Could not determine default remote git repository branch from env variable")
```
Comment (bacherfl) [inline resource-service/common/git.go:145]: let's use a different log level (e.g. debug) since it's not really an error if the env var is not set

File: resource-service/common/git.go [hunk 3]
```diff
@@ -135,12 +140,42 @@ func (g Git) storeDefaultBranchConfig(gitContext common_models.GitContext, err e
 	return nil
 }
 
+func retrieveDefaultBranchFromEnv(env envconfig.EnvConfig) string {
```
Comment (bacherfl) [inline resource-service/common/git.go:143]: this could also be a member function of `EnvConfig` -> just to reduce the verbosity of the git.go file a bit

**Review by bacherfl — APPROVED** [review]
