### PR TITLE
Set error to null when re-routing to project to hide previously shown…

### LINKED ISSUE #3804: "Project does not exist" pane does not vanish when navigating to a existing project
**Environment**
* 0.8.1 Bridge

**Affected Component**
* [ ] Bridge

**Describe the bug**
Project doesn't exist pane does not vanish when navigating to a existing project

**To Reproduce**

1. Navigate to not existing project e.g. /bridge/project/sockshoppe
    The screen shows, that the project does not exist
2. Click on 'Choose project' and select an existing project
3. The screen shows now both, the 'Project does not exist' and the project overview

**Expected behavior**
The 'Project does not exists' pane should vanish and only the project overview is visible

**Screenshots**
image

### PR DESCRIPTION
**Pull request by laneli**
Fixes #3804 
Signed-off-by: Elisabeth Lang <elisabeth.lang@dynatrace.com>

### CODE REVIEW

File: bridge/client/app/project-board/project-board.component.ts [hunk 1]
```diff
@@ -29,6 +29,7 @@ export class ProjectBoardComponent implements OnInit, OnDestroy {
     this.route.params
       .pipe(takeUntil(this.unsubscribe$))
       .subscribe(params => {
+        this.error = null;
```
Comment (ermin-muratovic) [inline bridge/client/app/project-board/project-board.component.ts:32]: Maybe it would be better to put it as `else` statement at https://github.com/keptn/keptn/blob/a2dd0b1b971ccfaa8cac00e8fc9c3139c7ea7d32/bridge/client/app/project-board/project-board.component.ts#L66-L67, so in case that the "Retry"-Button for some reason once returns `null` and then later a `project`, the error is also set to `null`

**Review by ermin-muratovic — CHANGES_REQUESTED** [review]

**Review by ermin-muratovic — APPROVED** [review]
lgtm
