### PR TITLE
fix(configuration-service): changed bad order of extracting and adding resources to services (#5975)

### LINKED ISSUE #5975: keptn add-resource with an invalid .tgz file makes your Keptn project unusable
This is with Keptn 0.10.0, and unfortunately, this is a very tricky one to describe (however, the fix should be easy):

When adding a `.tgz` file using `keptn add-resource` this file usually gets unpacked (unarchived) by configuration-service. This is used in order to add helm charts to Keptn, e.g.:

```
keptn add-resource --project=nodejs-example --service=hello-service --all-stages --resource=.keptn/helm/hello-service.tgz --resourceUri=helm/hello-service.tgz
```

However, if for whatever reason, the `.tgz` file is invalid (because of a user error!), we run into a lot of troubles.

# How to reproduce

Create a random file, e.g.
```console
echo "123" > my-service.tgz
```

Create a simple shipyard file, e.g.:
**shipyard.yaml**
```
apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-quality-gates"
spec:
  stages:
    - name: "hardening"
```

Create a project, and a service
```
keptn create project example --shipyard=./shipyard.yaml
keptn create service my-service --project example
```

Add the .tgz file as a helm chart
```
keptn add-resource --project=example --service=my-service --all-stages --resource=./my-service.tgz --resourceUri=helm/my-service.tgz
```

The last command fails with
```
Adding resource ./my-service.tgz to all stages of project example
Error: Resource ./my-service.tgz could not be uploaded: Could not unarchive Helm chart
```

If you try to access configuration-service and look into the git repo, you will see this:
```
kubectl -n keptn exec -it deployment/configuration-service configuration-service -- sh

cd /data/config/example
git status
```

```
On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	my-service/
```

For some reason, it is still possible to continue working (e.g., `keptn trigger evaluation`). In addition, the `.tgz` file seems to get added to the respective branches (hardening), but not extracted (because it's a faulty file).

# Expected behaviour

When adding a .tgz file as a resource and the extraction process fails, the git repo **must not** contain the `.tgz` file.

# Related code
https://github.com/keptn/keptn/blob/48fc51c1c2b4689b6658e36a8751d0d020c1912c/configuration-service/handlers/service_resource.go#L237-L264

### PR DESCRIPTION
**Pull request by odubajDT**
…g resources to services

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>

## This PR

- fixes bad order of extracting and adding resources to services
-  follow-up task: https://github.com/keptn/keptn/issues/6035

### Related Issues

Fixes #5975

### Notes

This issue is caused only by bad order of the actions when adding new resources to the service. Currently, by looping through the (helm) resource(s), the code actually adds the resource to the git repository and then tries to extract it. From my POV, we should first extract the file and check if it is valid and if yes, then add it to the repository.

### CODE REVIEW

File: configuration-service/handlers/service_resource.go [hunk 1]
```diff
@@ -208,15 +208,15 @@ func PostProjectProjectNameStageStageNameServiceServiceNameResourceHandlerFunc(
...
-
-		common.WriteBase64EncodedFile(filePath, res.ResourceContent)
 
 		if strings.Contains(filePath, "helm") && strings.HasSuffix(*res.ResourceURI, ".tgz") {
 			if resp := untarHelm(res, filePath); resp != nil {
 				return resp
 			}
 		}
+
+		logger.Debug("Adding resource: " + filePath)
```
Comment (warber) [inline configuration-service/handlers/service_resource.go:218]:
```suggestion
		logger.Debug("Adding resource: %s", filePath)
```

File: configuration-service/handlers/service_resource.go [hunk 2]
```diff
@@ -331,13 +331,15 @@ func PutProjectProjectNameStageStageNameServiceServiceNameResourceHandlerFunc(
...
-		logger.Debug("Updating resource: " + filePath)
-		common.WriteBase64EncodedFile(filePath, res.ResourceContent)
+
 		if strings.Contains(filePath, "helm") && strings.HasSuffix(*res.ResourceURI, ".tgz") {
 			if resp := untarHelm(res, filePath); resp != nil {
 				return resp
 			}
 		}
+
+		logger.Debug("Updating resource: " + filePath)
```
Comment (warber) [inline configuration-service/handlers/service_resource.go:341]:
```suggestion
		logger.Debug("Updating resource: %s", filePath)
```

File: configuration-service/handlers/service_resource.go [hunk 3]
```diff
@@ -331,13 +331,15 @@ func PutProjectProjectNameStageStageNameServiceServiceNameResourceHandlerFunc(
...
+		common.WriteBase64EncodedFile(filePath, res.ResourceContent)
```
Comment (warber) [inline configuration-service/handlers/service_resource.go:342]: does this func return an `error`, if yes, pls handle

File: configuration-service/handlers/service_resource.go [hunk 4]
```diff
@@ -208,15 +208,20 @@ func PostProjectProjectNameStageStageNameServiceServiceNameResourceHandlerFunc(
...
 			}
 		}
+
+		logger.Debug("Adding resource: ", filePath)
+		err := common.WriteBase64EncodedFile(filePath, res.ResourceContent)
+		if err != nil {
+			logger.WithError(err).Errorf("Could not add resource %s to project %s", filePath, params.ProjectName)
+			return service_resource.NewPostProjectProjectNameStageStageNameServiceServiceNameResourceBadRequest().
+			WithPayload(&models.Error{Code: 400, Message: swag.String("Could not add resource")})
+		}
```
Comment (thisthat) [inline configuration-service/handlers/service_resource.go:224]: I would wrap this code into a function since it is duplicated at line 345 and you can accept the action (update/add) as a parameter

Comment (odubajDT) [reply configuration-service/handlers/service_resource.go:224]: will make, thanks

File: configuration-service/handlers/service_resource.go [hunk 5]
```diff
@@ -175,6 +175,18 @@ func DeleteProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI
 	return stage_resource.NewPutProjectProjectNameStageStageNameResourceResourceURICreated().WithPayload(metadata)
 }
 
+func AddUpdateHelmResources(resource string, actionType string, filePath string, projectName string) middleware.Responder {
+	logger.Debug(actionType + "ing resource: ", filePath)
```
Comment (bacherfl) [inline configuration-service/handlers/service_resource.go:179]: `logger.Debugf( "%sing resource: %s", actionType, filePath)`

File: configuration-service/handlers/service_resource.go [hunk 6]
```diff
@@ -175,6 +175,18 @@ func DeleteProjectProjectNameStageStageNameServiceServiceNameResourceResourceURI
 	return stage_resource.NewPutProjectProjectNameStageStageNameResourceResourceURICreated().WithPayload(metadata)
 }
 
+func AddUpdateHelmResources(resource string, actionType string, filePath string, projectName string) middleware.Responder {
+	logger.Debugf("%sing resource: %s", actionType, filePath)
+	err := common.WriteBase64EncodedFile(filePath, resource)
+	if err != nil {
+		logger.WithError(err).Errorf("Could not %s resource %s to project %s", actionType, filePath, projectName)
+		return service_resource.NewPostProjectProjectNameStageStageNameServiceServiceNameResourceBadRequest().
```
Comment (bacherfl) [inline configuration-service/handlers/service_resource.go:183]: Imho this function should only return an error instead of also generating the complete http response object

Comment (odubajDT) [reply configuration-service/handlers/service_resource.go]: resolved

**Review by bacherfl — APPROVED** [review]
