### PR TITLE
fix(jmeter-service): Avoid nil pointer access when logging results

### LINKED ISSUE #7388: Integration tests failed
* Link to run: https://github.com/keptn/keptn/actions/runs/2106432759
* Triggered by: Scheduled build
* Branch: master
* Version: 0.15.0-dev.202204061209
* Datetime: 202204061209
* Commit: e5af97c9f

| Test                                                                   | GKE-1.19 | GKE-1.21 | k3s-on-GHA-v1.16.15+k3s1 | k3s-on-GHA-v1.21.1+k3s1 | k3d-on-GHA-v4.4.6 | minishift-on-GHA-3.11 |
| ---------------------------------------------------------------------- | -------- | -------- | ------------------------ | ----------------------- | ----------------- | --------------------- |
| Test_BackupRestoreConfigService                                        | :x: fail     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_GracefulShutdown                                                  | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_LogIngestion                                                      | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_LogForwarding                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceState                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceStateParallelStages                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceState_RetrieveMultipleSequence                            | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceState_SequenceNotFound                                    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceState_InvalidShipyard                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceState_CannotRetrieveShipyard                              | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceQueue                                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceQueue_TriggerMultiple                                     | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceQueue_TriggerAndDeleteProject                             | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceLoopIntegrationTest                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SelfHealing                                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ResourceServiceBasic                                              | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ManageSecrets_CreateUpdateAndDeleteSecret                         | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_Webhook                                                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_Webhook_OverlappingSubscriptions                                  | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_WebhookWithDisabledFinishedEvents                                 | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_WebhookWithDisabledStartedEvents                                  | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_WebhookConfigAtProjectLevel                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_WebhookConfigAtStageLevel                                         | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_WebhookConfigAtServiceLevel                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceTimeout                                                   | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceTimeoutDelayedTask                                        | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_Abort                                             | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_AbortQueuedSequence                               | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_AbortPausedSequence                               | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_AbortPausedSequenceTaskPartiallyFinished          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_AbortPausedSequenceMultipleStages                 | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_PauseAndResume                                    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SequenceControl_PauseAndResume_2                                  | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ZeroDownTimeTriggerSequence                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ResourceService                                                   | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_QualityGates                                                      | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_QualityGates_SLIWrongFinishedPayloadSend                          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_QualityGates_AbortedFinishedPayloadSend                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_QualityGates_ErroredFinishedPayloadSend                           | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_DeliveryAssistant                                                 | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_CustomUserManagedEndpointsTest                                    | :white_check_mark: pass     | :white_check_mark: pass     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ContinuousDelivery                                                | :x: fail     | :x: fail     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_UniformRegistration_TestAPI                                       | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_UniformRegistration_RegistrationOfKeptnIntegration                | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_UniformRegistration_RegistrationOfKeptnIntegrationMultiplePods    | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_UniformRegistration_RegistrationOfKeptnIntegrationRemoteExecPlane | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ProvisioningURL                                                   | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Keptn Install                                                          | :white_check_mark: pass     | :white_check_mark: pass     | :white_check_mark: pass                     | :white_check_mark: pass                    | :white_check_mark: pass              | :white_check_mark: pass                  |
| Keptn Auth                                                             | :yellow_circle: skip     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_BackupRestoreResourceService                                      | :yellow_circle: skip     | :x: fail     | :yellow_circle: skip                     | :yellow_circle: skip                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ResourceServiceGETCommitID                                        | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_EvaluationGitCommitID                                             | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_SSHPublicKeyAuth                                                  | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| Test_ProxyAuth                                                         | :yellow_circle: skip     | :white_check_mark: pass     | :yellow_circle: skip                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |
| TestAirgappedImagesAreSetCorrectly                                     | :yellow_circle: skip     | :yellow_circle: skip     | :yellow_circle: skip                     | :yellow_circle: skip                    | :white_check_mark: pass              | :yellow_circle: skip                  |
| Test_WebhookWithDisabledFinishedEvents#01                              | :yellow_circle: skip     | :yellow_circle: skip     | :white_check_mark: pass                     | :white_check_mark: pass                    | :yellow_circle: skip              | :yellow_circle: skip                  |

Note: This issue was auto-generated from [integration_tests.yml](.github/workflows/integration_tests.yml)

### PR DESCRIPTION
**Pull request by bacherfl**
Closes #7388

Integration test run: https://github.com/keptn/keptn/actions/runs/2107598753

Unfortunately the codecov diff check is failing, but in the service's current form we would need to add a test that actually performs a jmeter test using the jmeter CLI - which might be out of scope for the issue addressed with this PR

### CODE REVIEW

**Review by odubajDT — APPROVED** [review]

File: jmeter-service/jmeterUtils.go [hunk 1]
```diff
@@ -211,11 +211,10 @@ func execute(testInfo TestInfo, workload *Workload, err error, jMeterCommandLine
...
 	// Step 3: Parse result and lets analyze the result
 	result, err := parseJMeterResult(jmeterCommandResult, testInfo, workload, funcValidation)
-	if result && err != nil {
-		logger.Debugf("Successfully executed JMeter test: %v", testInfo)
-	} else {
-		logger.Errorf("Could not parse JMeter test (%v). Error: %s  ", testInfo, err.Error())
+	if err != nil {
+		logger.Errorf("Could not parse JMeter test (%v). Error: %v  ", testInfo, err)
 	}
+	logger.Debugf("Jmeter tests passed: %t. TestInfo: %v", result, testInfo)
```
Comment (mowies) [inline jmeter-service/jmeterUtils.go:217]: There's no return after the error message so I think we have a situation here where both error and success message could be printed at the same time

**Review by mowies — CHANGES_REQUESTED** [review]

**Review by mowies — APPROVED** [review]
